### ISSUE TITLE
Official Cloud Foundry docs missing info for webdav configuration.

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/capi-release#10]
The official stub documented for deploying Cloud Foundry on AWS includes stuff about webdav configuration:

https://github.com/cloudfoundry/cf-release/blob/fe6c99602c42fcc733ea75ff03f32040b176b346/spec/fixtures/aws/cf-stub.yml#L64-L95

But the documentation on how to fill out this stub doesn't explain how to fill out the values for replacement:

https://github.com/cloudfoundry/docs-deploying-cf/blob/master/aws/cf-stub.html.md.erb

/cc @utako @SocalNick

**Comment by SocalNick** [comment]
I happen to be working on this right now.

**Comment by SocalNick** [comment]
[Github Pull Request #100](https://github.com/cloudfoundry/docs-deploying-cf/pull/100)

**Comment by SocalNick** [comment]
@Amit-PivotalLabs @utako could you review?

http://docs-cloudfoundry-staging.cfapps.io/deploying/aws/cf-stub.html#webdav

**Comment by Amit-PivotalLabs** [comment]
Hey @SocalNick 

I generally think of those docs as providing the simplest possible way to create a stub to deploy Cloud Foundry.  I'd recommend having only one type of blobstore configuration in the `cf-release/spec/fixtures/aws/cf-stub.yml`, ideally the one that requires the least amount of external setup.  Then, in the documentation page that you edited, rather than adding a separate section on webdav, I would just add a row to the table with the snippet of the stub being explained in one column, and the explanation of the things to replace in the second column.  The explanation should be clear about how to replace the placeholder values (e.g. can the user just make them up, do they need to get the values to match some existing resource in their IaaS, etc.).  For more detailed documentation on possible webdav configurations, I would recommend working with the docs team to build a separate page, and then the stub documentation could link to that page telling users who want to do more advanced configuration to follow the link.

**Comment by aashah** [comment]
Judging from the tracker story, this seems to have been pushed and accepted already.

@Amit-PivotalLabs, feel free to re-open if there's anything further.

- @aashah, CAPI Team member
