### ISSUE TITLE
vendor golang and maybe ruby with bosh vendor package?

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/capi-release#103]
Hey y'all

Not so much of an issue as a `nice to have` - would be great if you switched your current golang/ruby packages that you've written the packaging for over to the bosh vendor package version of golang-release and ruby-release.

if you switch to [this](https://github.com/bosh-packages/golang-release/tree/master/packages/golang-1-linux) it should make it WAY easier for you to bump golang versions in the future (could even be automatically done in ci as `bosh vendor package` is idempotent. Unsure about ruby :/

[directions on bosh vendor package](https://bosh.io/docs/package-vendoring/#vendor)

[routing release as an example of the switch](https://github.com/cloudfoundry/routing-release/blob/develop/packages/gorouter/packaging#L3)

**Comment by selzoc** [comment]
@zachgersh we looked into this when we last bumped `go`, but it was very difficult to trace back the _actual_ version we were using.  This would help us when we get a story that's like "omg security upgrade to go 1.x.y".  With the vendored package approach, we have no way to tell after the moment that we vendor the package the actual version within.

**Comment by zachgersh** [comment]
@selzoc - have you run into a situation where you actually needed to know what version of go you were on because there was an incompatibility or a performance regression? On routing we've moved to an auto-bump strategy and it has seemed to work alright for us. It'd be nice from both a security and update strategy if we could all get there but I totally get it if some can't.

**Comment by cwlbraa** [comment]
@zachgersh :
> have you run into a situation where you actually needed to know what version of go you were on

@selzoc :
> when we get a story that's like "omg security upgrade to go 1.x.y"

**Comment by zachgersh** [comment]
@cwlbraa - but if you are bumping every minor continuously you are removing that threat model. So, the performance regression incompatibility was the more important part of that (not the security implications).

**Comment by cwlbraa** [comment]
https://github.com/bosh-packages/golang-release/issues/11

**Comment by charleshansen** [comment]
Sounds like we should go ahead and use the vendored golang since the version question is kinda answered. We can maybe do this at the same time as bumping to 1.11

**Comment by tcdowney** [comment]
@zachgersh as of 413377e5a81410c82dd4026b77a30b31415803a3 we're using the vendored Golang package. We have a separate story to try and use the vendored Ruby package [here](https://www.pivotaltracker.com/story/show/161737966).
