### ISSUE TITLE
Error filling in template 'logcache_tls_ca.crt.erb'

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/capi-release#105]
Hello,
we are using the ops file [disable-log-cache](https://github.com/cloudfoundry/cf-deployment/blob/v3.6.0/operations/disable-log-cache.yml) with our CF deployment. With CF v3.6.0 (capi-release 1.66.0) everything is running fine but with CF v4.4.0 (capi-release 1.68.0) we get the following error and we can't deploy:

```
Task 36511 | 07:46:35 | Preparing deployment: Preparing deployment (00:00:10)
Task 36511 | 07:47:00 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'api'. Errors are:
    - Unable to render templates for job 'cloud_controller_ng'. Errors are:
      - Error filling in template 'logcache_tls_ca.crt.erb' (line 1: Can't find link 'log-cache')
```

I guess this is because with capi-release 1.67.0 log-cache properties were introduced in the [cloud_controller_ng spec file](https://github.com/cloudfoundry/capi-release/blob/1f2c874a18c62fe86ee8b4a5d1bfcbddbb6281ba/jobs/cloud_controller_ng/spec#L28-L30).

**Comment by selzoc** [comment]
Hi @paolostivanin, thanks for raising this issue - we have just pushed a fix and expect it to be in the next capi-release!

Chris && @tcdowney
