### ISSUE TITLE
Allow operators to tune nginx

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/capi-release#106]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The nginx jobs used by cc and blobstore offer very limited tuning capabilities to operators. Such tuning, especially for the blobstore, is heavily dependent on the characteristics of the infrastructure CF is deployed on (chiefly, disk performance).

## Context

When many clients connect to our blobstores (e.g. during rolling cell updates) the blobstore is sometimes unable to serve all requests, and this can lead (in the worst cases) to CAPI itself become unavailable. We have already sent https://github.com/cloudfoundry/capi-release/pull/84 to partially alleviate the problem, but it would help if we were able to control some more nginx configs.

## Steps to Reproduce

Largely the same described in https://github.com/cloudfoundry/capi-release/issues/84

## Expected result

As an operator, I would like to be able to control the following directives (at least for the blobstore, but ideally also for cc):

`sendfile`
`sendfile_max_chunks`
`aio`
`read_ahead`
`directio`
`output_buffers`
`thread_pool`
`worker_processes`
`open_file_cache`
`open_file_cache_valid`
`open_file_cache_min_uses`
`open_file_cache_errors`

## Current result

Tuning directives are largely not exposed

## Possible Fix

- We could expose the configuration directives above to operators
- We could allow operators to inject blocks of custom directives (note that some of the options above can only be provided in specific contexts, so likely multiple injection points would be required)

Another option would be attempting to actually tune these options, but this would likely hurt certain CF users as the tuning would likely pessimize their workloads/infrastructure.

**Comment by charleshansen** [comment]
Sounds like a good idea. I'm not sure if I can prioritize this right now, but would take a PR for either just the blobstore or blobstore + cc.

I don't think I want to deal with the complication of multiple injection points, so I would prefer the solution where individual configuration directives are exposed.

If the nginx template is at all complicated, there should be some unit tests for it, similar to https://github.com/cloudfoundry/capi-release/blob/develop/spec/cloud_controller_ng/cloud_controller_ng_spec.rb

**Comment by selzoc** [comment]
@CAFxX @b10s any interest in submitting a PR as @charleshansen suggests?  Otherwise I don't think we will prioritize this work anytime soon.

**Comment by selzoc** [comment]
We would still accept a PR, but I'm gonna close this issue.
