### ISSUE TITLE
pre-start for blobstore takes too long (15-30 minutes)

### ISSUE THREAD

**Issue by giner** [cloudfoundry/capi-release#107]
## Issue

pre-start script may run for very long time (15-30 minutes) on big deployments which makes it impossible to push or restart applications during deploy

## Context

blobstore should have a lot of blobs stored

## Steps to Reproduce

`bosh recreate blobstore`

## Expected result

It should finish in about 1 minute

## Current result

It may take 15-30 minutes

## Possible Fix

Here is what takes a lot of time:
- https://github.com/cloudfoundry/capi-release/blob/251b2ceaddf0b450c9205bcc1cb229cf0298855f/jobs/blobstore/templates/pre-start.sh.erb#L22
- https://github.com/cloudfoundry/capi-release/blob/251b2ceaddf0b450c9205bcc1cb229cf0298855f/jobs/blobstore/templates/pre-start.sh.erb#L26

I'm not sure about a good fix because I don't know the reason to `chown` recursively every time in the first place.

**Comment by tcdowney** [comment]
@giner it's interesting that you're having trouble with that code -- we added it in June to address this exact issue. See:

* https://github.com/cloudfoundry/capi-release/issues/88
* https://github.com/cloudfoundry/cloud_controller_ng/issues/1013

You can also see some [benchmarks in this story](https://www.pivotaltracker.com/story/show/153199815) where we observed it being faster.

I've got some questions to help us troubleshoot this further:

1. What version of `capi-release` are you using?
1. Does this happen only on recreate or on every deploy?
1. How many files do you have in your blobstore?

Thanks,
Tim

**Comment by giner** [comment]
1. I was playing around with capi-release 1.61.0 which has all the changes related to pre-start.sh.
2. This happens when dentries and inodes are not in cache, e.g. when VM is just started or pagecache was extensively used recently so that dentries and inodes were purged from cache.
3. 292233 files is LAB (it takes around 14-15 minutes for cold start). Our PRO has 538890 files and I would expect the time to double but prefer not to know.

**Comment by giner** [comment]
> You can also see some benchmarks in this story where we observed it being faster.
I guess it was not a cold start.

**Comment by giner** [comment]
Here is how I'm going to work around it for until the issue is fixed:
```
git clone https://github.com/cloudfoundry/capi-release /tmp/capi-release
cd /tmp/capi-release
git checkout 1.61.0
git submodule update --init --recursive
patch -p1 << 'EOF'
diff --git a/jobs/blobstore/templates/pre-start.sh.erb b/jobs/blobstore/templates/pre-start.sh.erb
index 20b3140..e912d81 100644
--- a/jobs/blobstore/templates/pre-start.sh.erb
+++ b/jobs/blobstore/templates/pre-start.sh.erb
@@ -18,7 +18,8 @@ function setup_blobstore_directories {
   mkdir -p $data_dir
   mkdir -p $data_tmp_dir

-  local dirs="$run_dir $log_dir $store_dir $store_tmp_dir $data_dir $data_tmp_dir $nginx_webdav_dir ${nginx_webdav_dir}/.."
+  chown vcap:vcap $store_dir
+  local dirs="$run_dir $log_dir $store_tmp_dir $data_dir $data_tmp_dir $nginx_webdav_dir ${nginx_webdav_dir}/.."
   local num_needing_chown=$(find $dirs -not -user vcap -or -not -group vcap | wc -l)

   if [ $num_needing_chown -gt 0 ]; then
EOF
bosh create-release --name=capi-bs-fix --version=1.61.0-bs-fix --force
bosh upload-release --name=capi-bs-fix
```

**Comment by charleshansen** [comment]
Hi @giner, glad you have a workaround, even if it is a manual patch. 

Is this much faster for you even with a cold start?

We are still doing some archaeology into why we are chowning all of these files, but I don't think we need to be doing nearly this much.

**Comment by giner** [comment]
Hi @charleshansen,

With the chance it takes 1-2 minutes in all cases.

**Comment by selzoc** [comment]
Hi @giner , your patch seems pretty good!

By removing the `$store_dir` from the recursive `chown`, it seems like there's only 52 files/dirs to be `chowned`, consistently across a couple of environments I checked (not production environments).

We did some archeology and found that the reason that we even want to do a recursive `chown` was to ensure the transition from the `blobstore` running as `root` to running as the less-privileged user `vcap`.  Since that change was made ~2 years ago, we feel confident that being overly cautious here is no longer warranted, especially as we have reports that it takes a long time for folks such as yourself.

I did a test where I `chown`ed a package to `root` and then tried to create a build from it, and the error message is actually very clear as to what is going on:

```
~/workspace/cf-acceptance-tests/assets/staticfile
→ cf v3-create-package s
This command is in EXPERIMENTAL stage and may change without notice

Uploading and creating bits package for app s in org org / space space as admin...
package guid: 7c344681-ebb2-4f32-8880-db2268b335e7
OK

...

singleton-blobstore/76af3ed8-d262-4b24-a6c4-0ebccc36181a:
/var/vcap/store/shared/cc-packages/7c/34# chown root:root 7c344681-ebb2-4f32-8880-db2268b335e7

...

 → cf v3-stage s --package-guid 7c344681-ebb2-4f32-8880-db2268b335e7
This command is in EXPERIMENTAL stage and may change without notice

Staging package for s in org org / space space as admin...
Unexpected Response
Response Code: 500
Request ID:    66daad1b-b540-472e-4c24-370771b40400::d4b18e46-9e6a-4dbd-8247-7fd4e25e4ef5
Code: 0, Title: , Detail: {
  "errors": [
    {
      "detail": "Stager error: Could not get object, 403/",
      "title": "CF-StagerError",
      "code": 170011
    }
  ]
}
FAILED

...

singleton-blobstore/76af3ed8-d262-4b24-a6c4-0ebccc36181a:
/var/vcap/sys/log/blobstore# tail internal_error.log
2018/10/01 17:40:23 [error] 24#0: *36 open() "/var/vcap/store/shared/cc-packages/7c/34/7c344681-ebb2-4f32-8880-db2268b335e7" 
failed (13: Permission denied), client: 10.244.0.134, server: blobstore.service.cf.internal, 
request: "HEAD /admin/cc-packages/7c/34/7c344681-ebb2-4f32-8880-db2268b335e7 HTTP/1.1", host: "blobstore.service.cf.internal:4443"
```

Recovering from any of these errors is as simple as `chown vcap:vcap` the files listed.
