### ISSUE TITLE
CC clock fails to sync app processes, fails with vague certificate verification error

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/capi-release#121]
## Issue
In a Diego team CI environment, we noticed the `cf-apps` domain freshness was not being bumped due to failures to sync some app processes by the CC clock. Looking into the logs, we found log lines with the message `error-updating-lrp-state` and error message `Process Guid: <some-guid>: SSL_connect returned=1 errno=0 state=error: certificate verify failed`. However, this error only appeared to be occurring for a subset of the LRPs that existed on the foundation and other app pushes and task runs were succeeding during this time. We checked the expiry dates for all certificates in use on our foundation and did not find any that had expired. We also regenerated the CC mutual tls certs just in case but that did not resolve the issue. We tried before and after regeneration of those certs to use `curl` to talk to the BBS with mutual TLS and did so just fine. Finally, deleting orphaned CATs orgs/spaces/apps from this environment removed the sync issue and the `cf-apps` domain freshness was bumped correctly.

We would like to potentially see a more descriptive error as to what the certificate verification error actually is and maybe what component communication it came from (though the logs point to this being communication with the BBS somehow).

### Links
- the relevant CC code lives here: https://github.com/cloudfoundry/cloud_controller_ng/blob/105d5a7946354b623368f211d7d92033064b6a87/lib/cloud_controller/diego/processes_sync.rb#L19-L96

- Slack convo: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1547839621301100

### Logs
- the Diego team can provide logs via logit.io, however we only aggregate for 2 weeks so the relevant logs will expire around 2/1/19

## Steps to Reproduce
- N/A at this time, it is unclear what certificate was causing the error

## Expected result
- CC bumps the `cf-apps` domain freshness
- when it decides not to due to an error, it provides a detailed error message describing why certain communication with another component failed

## Current result
- CC is not bumping the `cf-apps` domain freshness
- the only error we can see is `Process Guid: <some-guid>: SSL_connect returned=1 errno=0 state=error: certificate verify failed`
- deleting the apps associated with the process guids in above verification errors solves the domain freshness issue for now

## Possible Fix
- include more detailed messages when certificate verification errors occur (the golang standard library style is a good example)

**Comment by tcdowney** [comment]
@sunjayBhatia what versions of `capi-release`/`cf-deployment` are you using in this test environment? Also are there any "interesting" things about this environment/affected apps?

E.g. do you run RATS (tcp routes in play), Windows stack apps, etc.

Thanks!

**Comment by sunjayBhatia** [comment]
@tcdowney This was on an environment with `capi-release` (`1.74.0`) and the `cf-deployment` develop branch version `1b92156b354b3f4fcde7bd0dc49da7c7d214057e` (I believe)

This is our "spicy" environment (`warp-drive`) that has a few experimental features enabled and we do run routing smoke + acceptance tests and two flavors of Windows CATs in CI

In terms of the affected apps, unfortunately I deleted them before we had a chance to take a look (I was mass deleting orphaned CATs orgs)

If you need to take a look at our configurations in more depth, we can provide them

**Comment by tcdowney** [comment]
Hmm, in that version we began logging out a partial backtrace along with the error. Did you see that included with the logs?

https://github.com/cloudfoundry/cloud_controller_ng/blob/3e6609b23bd6c4ba8a4ae295e965fc4ea48bb31f/lib/cloud_controller/diego/processes_sync.rb#L91

That would help us know which client was actually raising this error. Adding more information about why the certificate verification itself failed is difficult since the error is coming from a gem that's just bubbling up an OpenSSL error IIRC.

**Comment by sunjayBhatia** [comment]
@tcdowney here's an example of a full log line:
```
{"timestamp":1548191363.1600888,"message":"error-updating-lrp-state","log_level":"error","source":"cc.diego.sync.processes","data":{"error":"OpenSSL::SSL::SSLError","error_message":"SSL_connect returned=1 errno=0 state=error: certificate verify failed","error_backtrace":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `ssl_connect'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:41:in `initialize'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `new'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:26:in `create_socket'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:103:in `timeout'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'\n..."},"thread_id":70256558779380,"fiber_id":70256841207200,"process_id":1,"file":"/var/vcap/data/packages/cloud_controller_ng/3a6904fc1bfc7e10dcc6c5e1723520faa331dad7/cloud_controller_ng/lib/cloud_controller/diego/processes_sync.rb","lineno":91,"method":"block in process_workpool_exceptions"}
```

**Comment by tcdowney** [comment]
Ah, unfortunately our assumption that the first ten lines of the backtrace would be enough to debug was wrong. All that tells me is that it occurred in the generic httpclient library we use. 😢 I can see why you omitted that earlier!

I'm not sure why we decided to be so conservative with that logging (I imagine it was related to log bloat, but 🤷‍♂️), so I've pushed a branch to experiment with not truncating the backtrace.

**Comment by selzoc** [comment]
@sunjayBhatia we pushed the change to no longer truncate the log messages out of the process/task sync.  Next time this happens we should be able to troubleshoot better.

Do you want us to keep this open to track, or do you want to open another issue if it happens again?

Thanks,
Chris && @tcdowney

**Comment by sunjayBhatia** [comment]
@selzoc @tcdowney we can close this out if you like, we can come bother you with the stack trace again if it occurs again

**Comment by tcdowney** [comment]
Sounds good. The next capi-release (1.77.0) should include this change.

**Comment by ericpromislow** [comment]
This is caused by https://github.com/cloudfoundry/cf-deployment/issues/713 -- we submitted a PR to cf-deployment
