### ISSUE TITLE
Request a new capi release to include the latest aliyun fog library

### ISSUE THREAD

**Issue by superliblib** [cloudfoundry/capi-release#124]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Request a new capi release to include the latest (v0.3.3) aliyun fog library
Link to new releae: https://github.com/fog/fog-aliyun/releases/tag/v0.3.3

## Context

A few bugs fixed in aliyun fog library recently, and we would like to have a new cloud controller release so that cloudfoundry can leverage Aliyun blobstore, aka OSS

**Comment by tcdowney** [comment]
@superliblib 

Just bumped the `fog-aliyun` gem in https://github.com/cloudfoundry/cloud_controller_ng/commit/ec6d2942654f7419b6be6c53b5cc08ff4a849c5f so it should be available in the next `capi-release` (1.77.0).

For faster turnaround, feel free to make a pull request to https://github.com/cloudfoundry/cloud_controller_ng bumping it next time!
