### ISSUE TITLE
Migration fails with PG::TRDeadlockDetected: ERROR:  deadlock detected

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/capi-release#127]
## Issue

Migrations fail in postgres-backed CF deployments under load.

The errors looks like this:

```
PG::TRDeadlockDetected: ERROR:  deadlock detected
```
```
[2019-02-21 16:48:24+0000] /var/vcap/data/packages/cloud_controller_ng/ede20aef16642c0d2fe15c26498f2481a87ad72f/cloud_controller_ng/db/migrations/20181101211039_drop_and_recreate_app_space_org_labels.rb:16:in `block (2 levels) in <top (required)>'
```
```
[2019-02-21 17:50:15+0000] Caused by:
[2019-02-21 17:50:15+0000] PG::TRDeadlockDetected: ERROR:  deadlock detected
[2019-02-21 17:50:15+0000] DETAIL:  Process 45890 waits for AccessExclusiveLock on relation 16635 of database 16400; blocked by process 41298.
[2019-02-21 17:50:15+0000] Process 41298 waits for AccessShareLock on relation 308906 of database 16400; blocked by process 45890.
[2019-02-21 17:50:15+0000] HINT:  See server log for query details.
```

## Context

@andrew-edgar reported this in #capi slack here, and there's lots of convo around that. 
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1550771112024800
Also check out https://gocardless.com/blog/zero-downtime-postgres-migrations-the-hard-parts/ for technical deets. 

## Steps to Reproduce

Untested outside of IBM's realistic test environment, but perhaps if we load up operations that touch the app and space tables and then try to migrate through `migrations/20181101211039_drop_and_recreate_app_space_org_labels.rb`, we should see it deadlock.

## Expected result

Migrations go without a hitch.

## Current result

`PG::TRDeadlockDetected: ERROR:  deadlock detected`
migrations stop, deployment fails.

## Possible Fix

Many things have been floated:
1. 3 separate migrations (might not work for deployments that are passed this point)
2. drop the foreign keys prior to dropping the tables
3. comment out the original additions that add the tables, then make the migration that drops them aware of situations where they do not exist. (only possible because AFAIK they never landed in a release)

**Comment by sannidhi** [comment]
Hi @andrew-edgar 

Can you please let us know if this is still an issue? 

Also, have you been able to try this fix? https://github.com/cloudfoundry/cloud_controller_ng/blob/6d16edaef17422f51e0797526e6333fbd1fc8778/db/migrations/20181101211039_drop_and_recreate_app_space_org_labels.rb

- @reneighbor and @sannidhi

**Comment by monamohebbi** [comment]
@andrew-edgar mentioned in slack that they would be going forward with the 3 migrations fix.  Given our understanding of the issue, the `no_transactions` fix should essentially accomplish the same thing.  @ericpromislow ran a through a scenario that should simulate the issue with the fix and did not encounter any issues (as mentioned in the slack thread). 

We are going to mark this issue as resolved as the fix appears to work.

@sethboyles and @monamohebbi
