### ISSUE TITLE
Shared private domain is deleted silently if the original organization is deleted

### ISSUE THREAD

**Issue by giner** [cloudfoundry/capi-release#133]
If a private domain is shared with other organizations and the original organization is deleted the private domain is silently deleted.

Problems:
- There is no easy way to understand which organization is an owner of a private domain if a domain is shared
- Ownership of a private domain cannot be moved to another organization
- If the original organization is deleted domain becomes inaccessible for all organization it was shared with

```
$ cf create-domain stas2 test-domain.com
Creating domain test-domain.com for org stas2 as s.germanevtushenko@rakuten.com...
OK

$ cf share-private-domain stas3 test-domain.com
Sharing domain test-domain.com with org stas3 as s.germanevtushenko@rakuten.com...
OK

$ cf target -o stas3
$ cf domains
...
test-domain.com                           owned

$ cf delete-org stas2

$ cf domains
...
# test-domain.com no more
```

**Comment by cwlbraa** [comment]
https://apidocs.cloudfoundry.org/7.9.0/private_domains/retrieve_a_particular_private_domain.html

I agree that that isn't necessarily an _easy_ way, and I think we'd love to improve these rough edges in v3. There's a [draft proposal here](https://docs.google.com/document/d/1HbJU3zYwiMVveIh_I4rJFDf-1zd9DxUiwRm9FsaWe_s/edit?usp=sharing) that you might be interested in.

**Comment by selzoc** [comment]
@giner Did @cwlbraa answer your question?

**Comment by giner** [comment]
If the ideas from the proposal are implemented the problem will be solved.

**Comment by selzoc** [comment]
@Gerg were the ideas implements in v3 domains?

**Comment by Gerg** [comment]
Yes, currently the v3 endpoints do not let you delete a domain if it shared with other organizations. You will have to unshare it before deleting.

**Comment by selzoc** [comment]
Sounds like we can close this then!  Thanks for raising the issue @giner !
