### ISSUE TITLE
CAPI will need to set `cflinuxfs3` as the default stack before cf-deployment v8 release

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/capi-release#134]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CAPI uses `cflinuxfs2` as a default stack, which cf-deployment will cease support in April 2019. After cf-deployment v8 release, `cflinuxfs2` will no longer be available and `cflinuxfs3` will be the default stack available.

## Possible Fix

Please swap `cflinuxfs2` with `cflinuxfs3`

**Comment by tcdowney** [comment]
A few relevant links for anyone following along.

**cf-dev announcement:**
https://lists.cloudfoundry.org/g/cf-dev/topic/cflinuxfs2_cflinuxfs3/27835465

**cf-deployment release notes:**
https://github.com/cloudfoundry/cf-deployment/releases/tag/v7.9.0

**Comment by selzoc** [comment]
@Syerram we will make this default swap, but since we make our stacks and default stack configurable, you won't notice a difference in cf-deployment, since it's already configured there: https://github.com/cloudfoundry/cf-deployment/blob/17586d6fbc55755682645d0435e81659aec25cfa/cf-deployment.yml#L816-L821

**Comment by tcdowney** [comment]
This was done in this commit, will ship in the upcoming capi-release: https://github.com/cloudfoundry/capi-release/commit/29e85beef92c6b8fd9ae6760391afd5a0e619def

**Comment by tcdowney** [comment]
The following capi-release versions have removed the `cflinuxfs2` defaults:
* [1.79.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.79.0)
* [1.80.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.80.0)

Marking this issue as closed.
