### ISSUE TITLE
Bump NGNIX to 1.14

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/capi-release#135]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

NGINX 1.13 is an unstable branch and out of support upstream.

## Context

See https://nginx.org/en/download.html - NGINX 1.13 or 1.11 (odd numbers) aren't available for download anymore.

We've seen some issues with blobstore performance on Azure with certain Xenial stemcell versions (97.65 is fine, 97.66+ isn't), we aren't sure if root cause is Kernel-level, Nginx level, etc., however troubleshooting NGINX with the upstream OSS team would require a supported version.

**Comment by tcdowney** [comment]
@svrc-pivotal [capi-release 1.80.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.80.0) includes an update to  nginx `1.14.2`.

See 9bc44e2f9380c7e444da6afeb4b364a23e34b1f2 and 99fc03d9ae931187c184e162aae1c4e6ecc21f96 for the relevant commits. Thanks for reporting this!
