### ISSUE TITLE
Strange behavior while executing cf apps in different space under same org

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/capi-release#146]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We have an org which have multiple spaces and applications under it .
When we execute cf apps on one particular space we keep getting an error 

Getting apps in org q-platform / space idm as nsharma...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

This command give correct output and list of applications in different space under same org.

CF API "api_version":"2.78.0"

We are still on CF 256 release .

## Current result

REQUEST: [2019-06-05T20:53:45-04:00]
GET /v2/spaces/1b5a3191-a2a6-4107-937f-925884801477/summary HTTP/1.1
Host: api.x.x.x.x
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.38.0+7ddf0aadd.2018-08-07 / darwin

RESPONSE: [2019-06-05T20:53:46-04:00]
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 99
Content-Type: application/json;charset=utf-8
Date: Thu, 06 Jun 2019 00:53:46 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 2abe2329-94b3-4b50-9c2c-728f5dfe2842

{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by ericpromislow** [comment]
Hi @nsharmacovs 

Would you be able to find a traceback in the api logs that corresponds to that error? If it's repeatable, the easiest way to do this is by the following:

Connect to each of the API nodes you're running:
`bosh ssh api/X` for X in 0 1 2 ...
```
sudo su -
cd /var/vcap/sys/logs/cloud_controller_ng
tail -F cloud_controller_ng.log
```
Then rerun the `cf apps` command and see if the error message and traceback occurs in any of the log files. If so, the first two lines in the traceback are sufficient. No need to dump the full output here with possibly compromising information.

**Comment by selzoc** [comment]
This hasn't been updated in over a month, so closing.  Please re-open @nsharmacovs if you can attach logs!
