### ISSUE TITLE
Very large event meta-data on crash events causes DB issues

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/capi-release#152]
## Issue

Some crash events produce a very large meta data which can slow down the performance of the DB in a large environment

## Context

We are running CFD 6.8.0.   Sometimes the crash details are VERY large and the insert into the events tables when many of these are occuring can cause problems with postgres performance.

## Steps to Reproduce

have an app crash with a very large crash reason.  We saw some with up over 6507943 characters.

```
appcloud=# select max(char_length(metadata)), actee from events where created_at> '2019-08-20 16:00:00.000000' group by actee order by 1 desc ;
   max   |                actee
---------+--------------------------------------
 6507943 | 977261d9-b005-4049-ad13-2659f1911e90
```

## Expected result

Crash events can be inserted quickly and cause no performance degradation in the DB

## Current result

The insert of these large crash events caused problems with the DB performance

## Possible Fix

Prune the crash reason to a reasonable size.  In the diego DB it is 1024 characters.   But the event emitted and then picked up by TPS is the full stack / crash reason.   There are several places this could be trimmed..

1) in diego before the event is emitted from diego
2) in TPS before it creates the call to cloud_controller_ng to insert the crash event
3) in CC before it saves the information to the DB.

In a perfect world all the crash reasons would be small.  But when it's large most of the information is not that useful anyway.   

In diego would be the best since this would eliminate the amount of data sent over the network on the emitted event from diego to TPS and from TPS to CC.

**Comment by andrew-edgar** [comment]
https://github.com/cloudfoundry/bbs/blob/b740b1165ec04a171a892427ad5efd12a3a2dbf2/db/sqldb/actual_lrp_db.go#L414

This is the code in the BBS where they are trimming the crash_reason.

**Comment by cwlbraa** [comment]
This seems like a good improvement. @andrew-edgar do you have a good sense of what a good default would be? We'd like to save more information than Diego, ideally -- really as much as we can without the causing issues. Would you mind sharing some percentile statistics on the sizes? I imagine it's extreme outliers that are causing issues (99th percentile).

**Comment by andrew-edgar** [comment]
good point.  yeah I will try and get those numbers for you.  I agree it was mostly very large (over 200K characters) but let me get some more details.

**Comment by aashah** [comment]
Looking to tackle a lot of older issues.

@andrew-edgar if you still have context on this, I was wondering if you could help me figure out which part of the `metadata` json blob is actually contributing to the size. `metadata` is a blob, whose schema roughly looks like (pulled from our tests):

```json
{
            'instance' => Sham.guid,
            'index' => 3,
            'cell_id' => 'some-cell',
            'exit_status' => 137,
            'exit_description' => 'description',
            'reason' => 'CRASHED'
          }
``` 

Which of these fields is super large? Could you share a small example of one?

I think this would be an easy improvement to make!

**Comment by jspawar** [comment]
@andrew-edgar made a story in our backlog to address this: https://www.pivotaltracker.com/story/show/172708492

I think for now we'll probably just limit the size of the `exit_description` field in the crash event's metadata as Aakash pointed out, but let us know of course if you think we should modify that assumption
