### ISSUE TITLE
Client mismatch error when operator changes `app_ssh.oauth_client_id` property

### ISSUE THREAD

**Issue by staylor14** [cloudfoundry/capi-release#155]
## Issue

Altering [`app_ssh.oauth_client_id`](https://github.com/cloudfoundry/capi-release/blob/d4ad7fd7a999e769c2603f1e7fe053d6747af6f1/jobs/cloud_controller_ng/spec#L285-L287) results in inability to use `cf ssh` command due to UAA client mismatch error.

## Context

The `cf` CLI acquires the client id to use for its `ssh` command from the API's `info` endpoint.  If we allow operators to alter this id, the cli will use the altered id when it communicates with UAA for an authorization token.

The problem is that Diego's ssh-proxy job has hard-coded this field to "ssh-proxy" ([Slack thread here](https://cloudfoundry.slack.com/archives/C02FM2BPE/p1568314382044400)).  

When Diego's ssh-proxy presents the access token that we provide against the "ssh-proxy" UAA client, the UAA responds with a "mismatched client" error, and the `ssh` command fails.

## Steps to Reproduce

1. Clone existing `ssh-proxy` client (so we get the same authorities).  Name it `other-ssh-proxy`.
1. Set cloud_controller_ng.app_ssh.oauth_client_id = "other-ssh-proxy"
1. Re-deploy cf
1. `cf push` an app
1. `cf ssh` to the app

## Expected result

`ssh` to app instance succeeds.

## Current result

`ssh` to app instance fails with UAA error `UaaTokenEndpoint: Handling error: InvalidClientException, Client ID mismatch`

Love,
Steve and @bwasmith
cc @acrmp @abbyachau @n4wei @mariash

**Comment by selzoc** [comment]
I think we're ok with leaving the possibility open that misconfiguring the ssh property will break ssh.   
 I don't think we've ever heard of this actually happening.  Thanks for reporting the issue!

Chris && @christarazi

**Comment by acrmp** [comment]
@selzoc @christarazi Thanks. I think configuration of `app_ssh.oauth_client_id` to any value other than `ssh-proxy` is a misconfiguration.

If we want to support customising this value we need diego to also make this configurable, otherwise the property can probably be removed.
