### ISSUE TITLE
ccng_monit_http_healthcheck doesn't fail on status >=400, /healthz is rate limited

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/capi-release#166]
## Issue

Monit http health check succeeds no matter what http status is returned by /healthz endpoint.
/healthz endpoint is rate-limited. This leads to 429 on large landscapes with rather strict rate limits for unauthenticated access.

## Context

https://docs.google.com/document/d/1IVH-FOnPk9rbNEQ-IHiDMNn3QL-fnCr2xUPEbztDnB8/edit?ts=5e540534#

cf-deployment 12.23.0

## Steps to Reproduce

Configure cc.rate_limiter.enabled=true and a low cc.unauthenticated_limit (e.g. 20).
Observe 429 in CC logs for /healthz endpoint. E.g.;
```
Jan 31, 2020 @ 12:52:56.529	{"timestamp":1580475176.5292754,"message":"Completed 429 vcap-request-id: e9d0b8b7-8701-409e-9d4b-00b01d9b21c6","log_level":"info","source":"cc.api","data":{"request_guid":"e9d0b8b7-8701-409e-9d4b-00b01d9b21c6"},"thread_id":47225165720540,"fiber_id":47225165287060,"process_id":7,"file":"/var/vcap/data/packages/cloud_controller_ng/ad5c5fcdb060c1745aab8901073ebc0f9d2959f2/cloud_controller_ng/middleware/request_logs.rb","lineno":24,"method":"call"}
Jan 31, 2020 @ 12:52:56.510	{"timestamp":1580475176.5108457,"message":"(0.000620s) SELECT * FROM \"request_counts\" WHERE (\"user_guid\" = '127.0.0.1') LIMIT 1","log_level":"info","source":"cc.db","data":{"request_guid":"e9d0b8b7-8701-409e-9d4b-00b01d9b21c6"},"thread_id":47225165720540,"fiber_id":47225165287060,"process_id":7,"file":"/var/vcap/data/packages/cloud_controller_ng/ad5c5fcdb060c1745aab8901073ebc0f9d2959f2/gem_home/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/database/logging.rb","lineno":82,"method":"public_send"}
Jan 31, 2020 @ 12:52:56.507	{"timestamp":1580475176.507079,"message":"Started GET \"/healthz\" for user: , ip: 127.0.0.1 with vcap-request-id: e9d0b8b7-8701-409e-9d4b-00b01d9b21c6 at 2020-01-31 12:52:56 UTC","log_level":"info","source":"cc.api","data":{"request_guid":"e9d0b8b7-8701-409e-9d4b-00b01d9b21c6"},"thread_id":47225165720540,"fiber_id":47225165287060,"process_id":7,"file":"/var/vcap/data/packages/cloud_controller_ng/ad5c5fcdb060c1745aab8901073ebc0f9d2959f2/cloud_controller_ng/middleware/request_logs.rb","lineno":12,"method":"call"}
```
CC is not restarted.

In our foundations we have cc.unauthenticated_limit ~5k/h and up to 90 CC instances.

## Expected result

/healthz should return 200 even if # of /healthz calls for 127.0.0.1 exceeds configured rate limit for unauthenticated access.

monit http health check should fail on http status code >=400

## Current result

/healthz returns 429 and monit http health check doesn't fail.

## Possible Fix

Exclude /healthz check from rate limits similar to / and /v2/info endpoints.
Let the curl command in [ccng_monit_http_healthcheck.sh.erb](https://github.com/cloudfoundry/capi-release/blob/2f396a6e0d133e627926f3390fbae4694f5b4f34/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb) fail on an error response (--fail option).

**Comment by tjvman** [comment]
We're seeing this issue as well. We have rate limiting enabled in our environment with an unauthenticated rate limit of 1000.

Interestingly, the logs in `/var/vcap/sys/log/cloud_controller_ng/nginx-access.log` show that the request from the [monit healthcheck](https://github.com/cloudfoundry/capi-release/blob/2f396a6e0d133e627926f3390fbae4694f5b4f34/jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb#L46-L53), which goes to `<machine IP>:<port>/healthz`, gets a 200 response, but the request from the [route registrar check](https://github.com/cloudfoundry/capi-release/blob/2f396a6e0d133e627926f3390fbae4694f5b4f34/jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb#L9-L15), which goes to `localhost:<port>/healthz`, gets a 429 response.

Here's a snippet:
```
<machine IP> - [09/Mar/2020:15:38:36 +0000] "GET /healthz HTTP/1.1" 200 303 "-" "ccng_monit_http_healthcheck" <machine IP> vcap_request_id:094ad2cd-f9cb-4eba-bd00-72d3eaafc91c response_time:0.012
localhost - [09/Mar/2020:15:38:38 +0000] "GET /healthz HTTP/1.1" 429 316 "-" "curl/7.47.0" 127.0.0.1 vcap_request_id:f4a67c5b-8ebd-424c-be49-2336d22b0d67 response_time:0.004
```

**Comment by jspawar** [comment]
This seems reasonable to exclude the health check endpoint from rate limiting. I will look into this and create a story to track implementing this/use the story for this issue to track that implementation.

**Comment by jspawar** [comment]
@stephanme @tjvman made the change to allow `/healthz` to bypass rate-limiting: https://github.com/cloudfoundry/cloud_controller_ng/commit/8ab6e354a5b65836c4fa5f9e0c7d685b721a7188

**Comment by Gerg** [comment]
I'm curious if we want monit (and routing) health checks to fail based on http status codes. It seems like we are opening ourselves up to situations where CCs reboot even if there are non-critical issues. For example, in this case, turning on rate-limiting would have caused CCs to enter boot loops even though CC was otherwise healthy.

That said, if the healthz had logic that intentionally returned status codes other than `200`, then it might make sense to branch on.

**Comment by stephanme** [comment]
I think that CC should be restarted on bad http status codes for the health endpoint, at least on all 5xx status codes. 4xx is not supposed to happen as the health check is a static, valid, anonymous and (now also) non-rate-limited request.

AFAIK, the CC health endpoint doesn't involve requests to the CC DB. This also means that that there is no restart on DB problems where (usually) a restart of the CC would not help anyway.

We observed that the CC health endpoint depends indirectly on DB downtimes and also CC overloads: the remaining working CC VMs can't handle the load anymore and reach the max 20 requests that can be in-flight concurrently. Then CC can't work on health check requests as well and it gets restarted. On a DB downtime the restarts don't help but don't do any harm either. On overload situations, the restarts are counter-productive and can increase the overload situation (retries by clients on aborted requests). But the health check can hardly distinguish between an global CC overload due to bad scaling and a local issue on a CC VM that results in hanging request processing -> restart is the best option.

**Comment by Gerg** [comment]
What are some cases where restarting CC on a 5XX response would be helpful? I agree that it wouldn't be harmful in the cases you described, but I don't understand the benefits.
