### ISSUE TITLE
Package ruby-2.4.6-r0.9.0 obsolete

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/capi-release#168]
## Issue

Package `ruby-2.4.6-r0.9.0` seems to be obsolete, since it is not referenced by any job.

## Context

https://github.com/cloudfoundry/capi-release/tree/develop/packages/ruby-2.4.6-r0.9.0

## Possible Fix

Remove the package.

**Comment by aashah** [comment]
Thanks for noticing this haha, silly human error I guess.

Just removed it (forgot to tag in commit though - 0ba2dc8122d19ecff), thanks.
