### ISSUE TITLE
Hard to debug service broker CATS test

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/capi-release#17]
Adding this issue here instead of `cf-acceptance-tests` repo to give visibility to the CAPI team.

We have a failed CI job which runs cf-acceptance-tests against a CF deployment: https://runtime.ci.cf-app.com/pipelines/cf-release/jobs/a1-diego-cats/builds/65

```
• Failure in Spec Setup (BeforeEach) [314.151 seconds]
Service Instance Lifecycle Asynchronous operations [BeforeEach] when there is an existing service instance can delete a service instance 
/tmp/build/357ec5d1/gopath/src/github.com/cloudfoundry/cf-acceptance-tests/services/service_instance_lifecycle_test.go:379

  Timed out after 300.000s.
  Expected process to exit.  It did not.

  /tmp/build/357ec5d1/gopath/src/github.com/cloudfoundry/cf-acceptance-tests/helpers/services/broker.go:116
```

It appears to take > 5 minutes to `cf start`.  Most tests do an `AppReport` after a `cf start` fails which does a `cf logs --recent` dump.  This is very useful because the timestamps help tell the story of what exactly is taking too long (creating container, downloading blobs, uploading blobs, fetching Ruby gems, etc.).  That would be desirable here, might be difficult given the structure of the broker DSL.

Generally seems undesirable to have lots of orchestration and assertions hidden inside test helpers.

**Comment by adowns01** [comment]
Hello @Amit-PivotalLabs, 

Can you point us to the line where `cf start` is happening? We would like to include the AppReport logs but the failing test does not seem to be starting an app.

Thanks,
@adowns01 && @youreddy

**Comment by Amit-PivotalLabs** [comment]
https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/helpers/services/broker.go#L116

https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/services/service_instance_lifecycle_test.go#L283

**Comment by Amit-PivotalLabs** [comment]
Any update on this? This would still be useful for improving ability to debug CATS failures.

**Comment by luan** [comment]
We believe we address this issue on https://github.com/cloudfoundry/cf-acceptance-tests/commit/19865ccb3808eb055dfd9d829fe0a92f7746123a. Feel free to re-open this issue if you believe there's more to be done here.

Thanks,
@luan | @youreddy,
CF CAPI Team
