### ISSUE TITLE
Bump nginx to 1.17.7 to clear compliance findings

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/capi-release#173]
## Issue

Nessus, https://www.tenable.com/plugins/nessus/134220, now considers use of Nginx < 1.17.7 a medium risk information disclosure. Bumping nginx to 1.17.7 or greater would clear this finding.

## Context

https://github.com/cloudfoundry/capi-release/blob/develop/config/blobs.yml#L33 show nginx is 1.16.1

## Possible Fix

Bump https://github.com/cloudfoundry/capi-release/blob/develop/config/blobs.yml to newer nginx.

**Comment by pburkholder** [comment]
Hi! Any update on getting this version bumped? Thanks, Peter

**Comment by selzoc** [comment]
Hi, we'll bump the version, but digging into the CVE, we're not vulnerable to this (it depends on configuring the `error_page` directive.

**Comment by pburkholder** [comment]
Thanks much -- this makes my life _so_ much easier compared to going to Nessus to complain about their false positives, or to our authorization board to document this as a false positive. I appreciate the help. 

Also, it's probably not a bad thing to have a newer version.

Cheers, Peter

**Comment by selzoc** [comment]
Yes!  Thank you for the reminder to bump this anyhow :)

**Comment by pburkholder** [comment]
Hello - my compliance calendar obliges me to ask monthly: Any progress here on bumping the nginx version?

**Comment by selzoc** [comment]
Hi @pburkholder !  I have made this bump and it's currently wending its way through our pipleine: https://github.com/cloudfoundry/capi-release/commit/0fb26eec911bc237b708c28dbbbb3173802f0b7c

I expect it to land in the next capi-release

**Comment by pburkholder** [comment]
Sorry for the extra notification, but leaving this comment to document that I've check on the status of this. Carry on with your regularly scheduled day :wave:

**Comment by selzoc** [comment]
Happy friday @pburkholder !  We have recently shipped https://github.com/cloudfoundry/capi-release/releases/tag/1.97.0 which incorporates this bump.
