### ISSUE TITLE
No Docker-Support in Manifest-File

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/capi-release#18]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Sadly there is no way to define a Docker-image in manifest.yml at the moment.
Instead you have to define it on every cf push, via -o.

## Possible Fix

Add anything like docker_image to manifest.yml
Would be awesome!

**Comment by SocalNick** [comment]
Hi @elgohr,

The application manifest is actually a CLI construct and is never processed by the Cloud Controller API server. You'll want to start a conversation with the CLI team: https://github.com/cloudfoundry/cli/issues

-Nick
