### ISSUE TITLE
Buildpack cannot be null anymore?

### ISSUE THREAD

**Issue by szihai** [cloudfoundry/capi-release#190]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue
Nullpointer exception at org.cloudfoundry.operations.applications.ApplicationManifest
We just upgrade our cf java api from 3.1.2 to 5.1.0 and noticed in the new version, buildpack cannot be null anymore.

## Context

So our code will pass the manifest fields to cf api. Since CF can figure out the proper buildpack by itself, we don't fill in that field in case different spaces have different buildpacks installed. But now the now the code is broken. And we would like to know a little bit more about why such change is necessary and how to work around it.

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/26101651/111004313-a803d800-833d-11eb-8331-752e84bc3d17.png)

**Comment by philippthun** [comment]
This issue should go to https://github.com/cloudfoundry/cf-java-client, I guess.
