### ISSUE TITLE
Monit healthcheck exit code logging does not work

### ISSUE THREAD

**Issue by andy-paine** [cloudfoundry/capi-release#194]
## Issue
When the `curl` in the monit http healthcheck script fails, it logs that the curl exited `0` when it actually exited something like `7`

## Context
The `curl` command that is used to check when Cloud Controller is no longer responding to healthchecks is handled inside an `if ! curl ...` block so that failures do not trigger the `set -e` and exit immediately. Unfortunately this seems to result in `$?` holding the exit code of the `if` (which is always `0`) so the script logs that curl exited with `0` and CC is being restarted which is a bit confusing

## Steps to Reproduce
* Run the `ccng_monit_http_healthcheck.sh` script
* Stop the main cloud_controller_ng process
* Observe logs from `ccng_monit_http_healthcheck.sh` script

## Expected result
* Logs show that curl exited with code `7`

## Current result
* Logs show that curl exited with code `0`

## Possible Fix
a) Run and capture exit code of `curl` outside of `if` (this is awkward since we have `set -e` on so failing `curl` invocations will exit script immediately)
b) Use bash `||` to handle failures e.g. `curl ... || { status=$?; echo "exited $status"; exit $status; }`
c) Don't bother logging the exit status of `curl` - it has been broken all this time stating it is `0` so maybe just remove the logging entirely then we can just run the `curl` as normal and `set -e` will handle exiting with the right code

**Comment by philippthun** [comment]
Fixed with f22e7e092eda7172ec7cd8afff2c29b68750525a.

**Comment by sethboyles** [comment]
this fix was released in capi-release 1.111.0
