### ISSUE TITLE
cf-acceptance-tests services tests don't provide output logs

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/capi-release#22]
I have several flaky service instance lifecycle tests.  The code looks deterministic, namely that when create an asynchronous service instance, the fake broker should first respond saying that it is in_progress, and then respond saying it's complete.  It appears to continue saying it's in_progress.  We were wondering if there was some caching of the response happening anywhere, and wanted to check if requests were making it all the way to the service broker app.  We see the requests making it to the router.  The problem is the CATS in question don't dump the service broker app's logs when the test fails.

**Comment by adowns01** [comment]
Are you talking about running CATs in a pipeline? We have a job that uploads our CAT logs to S3 which you could add to your pipeline. 

https://github.com/cloudfoundry/capi-ci/blob/master/ci/pipeline.yml#L337

**Comment by Amit-PivotalLabs** [comment]
Those logs are typically CF_TRACE logs from the CLI.  I'm talking about logs of the pushed app itself, i.e. the stuff from `cf logs MY_APP --recent`.  Most tests leverage an `AppReport` helper which dumps logs of an app on teardown, but not true of the service brokers.

**Comment by Amit-PivotalLabs** [comment]
Any update on this?  This would still be useful for improving ability to debug CATS failures.

**Comment by luan** [comment]
We believe we address this issue on https://github.com/cloudfoundry/cf-acceptance-tests/commit/19865ccb3808eb055dfd9d829fe0a92f7746123a. Feel free to re-open this issue if you believe there's more to be done here.

Thanks,
@luan | @youreddy,
CF CAPI Team
