### ISSUE TITLE
Evaluate impact of thin_server.thread_pool_size 

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/capi-release#221]
#### depends on
- [ #2254](https://github.com/cloudfoundry/cloud_controller_ng/issues/2254) Just makes sense in case we dont use puma

## Context

Currently each CC allows 20 concurrent http connections by default(even if they are just pseudo concurrent cause it runs in a single thread).  Can increasing this value help to reach better or more stable throughput even in short overload situations ?

## Acceptance Criteria

- [ ]  We have a document showing how changing this parameter influences 1. throughput and 2. performance

**Comment by philippthun** [comment]
We will switch to Puma eventually, so this is not going to happen.
