### ISSUE TITLE
support for stemcell Ubuntu Jammy Jellyfish

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/capi-release#223]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Stemcells based on Ubuntu Jammy (22.04) are currently in Alpha, but the package mariadb_connector_c does not compile.

## Context

I tried to deploy cf-deployment (which contains capi release) with the new Jammy stemcell, but it fails to compile the mariadb_connector_c package. I will attach the log file which has all the compile errors.

## Steps to Reproduce

Do a bosh deployment for a deployment that has the capi-release (cf-deployment for example) with the Jammy stemcell.

## Expected result

I expect a clean successful compile

## Current result

The compile fails, see attached log file.

## Possible Fix

Maybe
[mariadb_connector_c.log](https://github.com/cloudfoundry/capi-release/files/7944449/mariadb_connector_c.log)
 upgrading to mariadb_connector_c version 3.1.13 ? [https://mariadb.org/download/?t=connector&p=connector-c&r=3.1.13&os=source]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by metskem** [comment]
Also the package ruby-2.7.2-r0.41.0 does not compile on Jammy, I will attach another logfile for that.
[ruby.log](https://github.com/cloudfoundry/capi-release/files/7948552/ruby.log)

**Comment by sethboyles** [comment]
Thanks for the report.  Seems [like we need Ruby 3.1](https://bosh.io/docs/jammy-migration/#openssl-3), which will take a significant effort to get to.  Thankfully we are already in the process of upgrading to Ruby 3.0: https://github.com/cloudfoundry/cloud_controller_ng/pull/2623

**Comment by sethboyles** [comment]
So it's complicated, but there are ways to get Ruby 2.7 to work with Jammy: https://github.com/bosh-packages/ruby-release/pull/27

Some more info (copied from slack):

As far as I can tell there are some subtleties to the Ruby 3.1/OpenSSL3 situation:
* The [OpenSSL gem purports to support Ruby >2.6](https://github.com/ruby/openssl/blob/master/openssl.gemspec#L18)
* [OpenSSL 3.0 support is preliminary and not all features are currently available](https://github.com/ruby/openssl/blob/master/History.md#compatibility-notes) 
* Ruby 3.1 doesn't seem to be the only version of Ruby that supports OpenSSL 3.0, but it is the only one that bumps the OpenSSL gem to 3.0, which includes the (partial) OpenSSL 3.0 support.  I'm guessing this is what causes Ruby 2.7 compilation to fail?  Theoretically you could install Ruby 2.7 with OpenSSL 1.1 then upgrade to OpenSSL 3.0 afterward?

**Comment by cunnie** [comment]
@sethboyles Let me know if you can fix running CAPI on Jammy without going all the way to Ruby 3.1—I'll update the [documentation](https://bosh.io/docs/jammy-migration/) with your solution.

Also, another-but-unrelated fix would be to bump the nginx BOSH package in CAPI release to 1.21.6.

**Comment by sethboyles** [comment]
This work was initially completed with https://github.com/cloudfoundry/capi-release/releases/tag/1.134.0
