### ISSUE TITLE
nsync fails to update desired state in BBS silently

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/capi-release#24]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

nsync fails to update desired state in BBS silently.

## Context

If `capi.nsync.cc.base_url` is provided without a protocol, e.g. `api.system-domain.com` instead of `https://api.system-domain.com`, then rather than failing fast at deployment time, the bulker will continually fail to update freshness because of an invalid scheme `""`.

Eventually, stale LRPs are left around in Diego and aren't GC'd, leading to insufficient resources.

## Steps to Reproduce

Deploy CF + Diego with `capi.nsync.cc.base_url` set to `api.YOUR_SYSTEM_DOMAIN` without any `http://` or `https://` scheme in the URL.

## Expected result

When misconfiguring the URL like this, I'd expect to nsync to fail on the deployment, since the configuration it has been given is bad and will never work.

## Current result

Currently nsync deploys correctly, and only after a long time do I eventually see lots of app pushes fail due to insufficient resources.

## Possible Fix

Validate the input in the startup or pre-start scripts, and fail fast if the input is invalid.

**Comment by adowns01** [comment]
Hi Amit,

done! 8296a1a7304db7628472e6766bf5453b0573e940

If this solves your problem, please close this issue.

Thanks, Amelia

**Comment by Amit-PivotalLabs** [comment]
Haven't tested it out, assuming it works.
