### ISSUE TITLE
Logging Rate Limits - Allow operators to better control log production

### ISSUE THREAD

**Issue by klakin-pivotal** [cloudfoundry/capi-release#245]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CF Operators are sometimes unhappy about the performance of the logging system in CF. We propose to add a system to permit operators more-fine-grained control over Application log handling.

We've work underway to add this system. This Github Issue serves to help track that work. We're not requesting that someone else address the issue; we believe we have it under control.

## Context

The full context can be read here:
https://docs.google.com/document/d/1BEdtKHJ877Cn4HOfvAzIdMwoD0dpZuzRNBsmQ7c5_zM/edit#heading=h.sa8b0ujnd2tn

**Comment by klakin-pivotal** [comment]
cc: @cloudfoundry/runtime

**Comment by sethboyles** [comment]
I think we can close this now, now that https://github.com/cloudfoundry/cloud_controller_ng/pull/2900 has been merged and released

**Comment by mogul** [comment]
@klakin-pivotal can you please open access to the referenced Google Doc?

**Comment by ctlong** [comment]
Unfortunately, I can't access that doc either anymore. Since this feature was completed though, much of the information in that doc should now be in public docs, e.g. https://docs.cloudfoundry.org/loggregator/app-log-rate-limits.html.

**Comment by mogul** [comment]
Oh I hadn't seen that. Thanks!
