### ISSUE TITLE
After introducing new state "initial" in cf service, our applications are failing

### ISSUE THREAD

**Issue by VedaReddivari** [cloudfoundry/capi-release#250]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

After introducing new state "initial" in cf service, our applications are failing

## Context

some of the functionality, our application flow is dependent on the 3 states of the (in-progress , succeeded, Failed) , Now with this new state (initial) , functionality is failing.

This was not mentioned in CF V3 documentation or didn't see any release notes for either cf-deployment capi-release notes

## Steps to Reproduce

Create the CF service and verify the states

https://github.com/cloudfoundry/cloud_controller_ng/pull/2836

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot
![image](https://user-images.githubusercontent.com/86948965/178187794-32a073ac-c34e-4e33-b9bc-6d3430942822.png)

![image](https://user-images.githubusercontent.com/86948965/178187809-2f69699f-6813-4b66-a9f0-524171bd5eb9.png)

**Comment by philippthun** [comment]
Duplicates https://github.com/cloudfoundry/cloud_controller_ng/issues/2862
