### ISSUE TITLE
"cf disable-diego" for Docker app results in confusing error message [migrated from diego-release]

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/capi-release#28]
> Original issue: https://github.com/cloudfoundry/diego-release/issues/199
> Original poster: @jochenehret

---

Hi Diego developers,

when we push a Docker app to Diego and then call `cf disable-diego <appname>`, we get a confusing error message and the app status is inconsistent:
```
$ cf disable-diego lattice-app
Setting lattice-app Diego support to false
FAILED
Error: CF-AppPackageNotFound - The app package could not be found: 92e75ab6-d631-4069-9fb5-c6cd1dfedd6a
{
   "code": 150002,
   "description": "The app package could not be found: 92e75ab6-d631-4069-9fb5-c6cd1dfedd6a",
   "error_code": "CF-AppPackageNotFound"
}
```
The app is not listed in `cf diego-apps` any more, but still running. The status is inconsistent:
```
$ cf apps
Getting apps in org test / space diego-test as admin...
OK

name           requested state   instances   memory   disk   urls
lattice-app    started           ?/1         1G       1G     lattice-app.cfapps.hcp-dev04.aws.sapcloud.io
```
I know that it doesn't make sense to disable Diego for Docker apps, but can you still try to provide a better error message?

Thanks and Best Regards,

  Jochen.

**Comment by SocalNick** [comment]
Fixed here: https://www.pivotaltracker.com/n/projects/966314/stories/130969997
