### ISSUE TITLE
No support for Security Group definition updates

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/capi-release#30]
This is a re-opening of #9 
## Issue

When you change existing SG definitions in cf manifest or add new security groups and apply changes with BOSH, the changes are not applied even though instances are updated by BOSH. Behaviour looks similar to https://github.com/cloudfoundry/capi-release/issues/4
## Context

I want to update existing SG or add new SG.
## Steps to Reproduce

Update existing SG or add new SG in CF manifest. Bosh deploy, watch BOSH update controller VM.
## Expected result

Changes are applied and new SGs exist when you do `cf security-groups`.
## Current result

Changes are not applied and no new security groups are created.
## Possible Fix

Either apply changes or at least document that even though changes from manifest are applied against environment, your release is ignoring them.
## Versions

BOSH v255.8, CF v233

**Comment by SocalNick** [comment]
@mtekel thanks for re-submitting. I took a second look at the code and I think we can update security groups with the same name and create new security groups. Deletion would obviously be dangerous.

However, as users are accustomed to the current behavior, we would have to add a flag, something like `cc.reseed_security_group_definitions` that would be `default: false`. 

This is more of a feature request than an actual issue and is not a high priority for our team. Would you be interested in submitting a PR?

**Comment by mtekel** [comment]
Hi,

the issue here is that it is unexpected (because it is undocumented) that currently, when you change these groups, BOSH will apply changes to controller, but controller will do nothing. As a user/operator you expect changes (to SGs) are also applied...

**Comment by michaelxupiv** [comment]
Hello @mtekel,

Manifest properties such as `cc.default_running_security_groups` are meant for initially seeding the database. We recommend that operators modify and add security groups using the API after this and not via the manifest, as using the API includes features like logging.

We agree that this could be documented more clearly. We've written a [story](https://www.pivotaltracker.com/story/show/133558645) to address this.

Thanks,
@michaelxupiv & @utako , CAPI Team
