### ISSUE TITLE
No support for Quota definition updates

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/capi-release#31]
This is a re-open of #4 

AFAIK this has not been addressed. At least updating documentation would be nice (where you would explicitly list all kinds of bootstrap things like quotas, security groups etc.).

**Comment by SocalNick** [comment]
Same as https://github.com/cloudfoundry/capi-release/issues/30#issuecomment-256118109, would you consider making a PR to fix or possibly opening a PR to clarify [the documentation](https://docs.cloudfoundry.org/adminguide/quota-plans.html#modify) to say quotas can only modified before the initial deploy

**Comment by mtekel** [comment]
Doc PR: https://github.com/cloudfoundry/docs-cf-admin/pull/43
