### ISSUE TITLE
pre-start.erb.sh chown code is redundant

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/capi-release#32]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.
## Issue

In blobstore's `pre-start.sh`  , `chown` is doing more work than it needs to.
## Context

In this line:

```
chown -R vcap:vcap $run_dir $log_dir $data $tmp_dir $nginx_webdav_dir "${nginx_webdav_dir}/.."
```

`chown` is running over `/var/vcap/packages/nginx_webdav` twice
## Steps to Reproduce

Use two terminal windows.  One to deploy cf, and the other to ssh into the VM
and watch the processes.  Run something like `watch -c 'ps auxww | grep chown | grep -v -e grep -e watch`
## Expected result

`chown` should run for about 5 seconds
## Current result

`chown` runs for about 5 minutes. This is because the `nginx_webdav`
package doesn't need any preprocessing, so `/var/vcap/packages/nginx_webdav` is a
symlink to `/var/vcap/packages-src/HASH` and therefore `"${nginx_webdav_dir}/.."` 
resolves to `/var/vcap/packages-src` which contains the full complement of CF
packages.
## Possible Fix

The reference to `"${nginx_webdav_dir}/.."` is a code smell.
If you really want to `chown -R` both dirs, it would be better to write the code like this:

```
local packages_dir=/var/vcap/packages
local nginx_webdav_dir=$packages_dir/nginx_webdav
...
chown ... $nginx_webdav_dir $packages_dir
```

**Comment by ericpromislow** [comment]
PR https://github.com/cloudfoundry/capi-release/pull/33

**Comment by luan** [comment]
PR has been closed, closing this too.
