### ISSUE TITLE
No support for Quota definition updates

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/capi-release#4]
I have reported the issue in BOSH (see full description: https://github.com/cloudfoundry/bosh/issues/1201), but likely it can be fixed by changing the way updates are handled by the CC scripts in this release.

**Comment by utako** [comment]
Hi @mtekel,

The ability to update your quota definitions through your manifest is not a feature we currently support. We'd like operators of CF to be able to seed their databases using the manifest quota_definition manifest properties, but after this initial seeding, all updates should be done through the API. 

We've updated the quota_definitions description in the cloud controller [spec file](https://github.com/cloudfoundry/capi-release/commit/310e0d09fcdf0d251c3fa985629cb466732ec422) for clarity.

Feel free to reopen this issue if you have any other concerns.

@utako and @simonleung8, CF CAPI Team

**Comment by mtekel** [comment]
@utako 

Thanks for your reply. I think you should document this properly (a small change in spec file is not enough), as the concept of BOSH and manifest in general is that you define your settings in manifest and BOSH applies them. So when I change `default` quota and run BOSH apply - which succeeds, I expect my quota to be changed.

You should rename all the properties (from `default_quota_definition` and `quota_definitions` to e.g. `seed_quota` definition and `create_once_quotas`). You should also talk to BOSH people for them to develop a feature flag, which you can add to properties in the manifest to tell BOSH that it needs to ignore and not apply changes in these properties as they would be ignored.

Most importantly, you should document this **IN BOLD RED LETTERS** in the documentation, as this is definitely against the expected behavior.

**Comment by mtekel** [comment]
btw. I can't re-open this.... I think you should create new issue in BOSH to develop `ignore_changes` flag and a new issue for you to document this properly...

**Comment by alext** [comment]
@utako Currently the docs (https://docs.cloudfoundry.org/running/managing-cf/quota-plans.html#modify) say that it's possible to modify a quota by updating the definition in the manifest. In our testing, this doesn't work as described.
