### ISSUE TITLE
isolation segment feature [migrated from diego-release]

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/capi-release#41]
> Original issue: https://github.com/cloudfoundry/diego-release/issues/247
> Original poster: @YunSangJun
---

I have tested isolation segment feature on follow cf version.
- cf v250
- Diego release v1.4.1. Release notes for v1.4.1 · v1.4.0 · v1.3.1 · v1.3.0.
- Garden-Runc release v1.0.4. Release notes for v1.0.4.
- cflinuxfs2-rootfs release v1.44.0. Release notes for v1.44.0 · v1.43.0 · v1.42.0.
- stemcell 3312.12

I found api which bind segment to org but there is no api that bind segment to space.
http://v3-apidocs.cloudfoundry.org/version/3.3.0/#entitle-one-or-more-organizations-for-an-isolation-segment

When do you plan to release the api?

**Comment by thausler786** [comment]
@YunSangJun,

The current way to bind an isolation segment to a space is through the `/v2/spaces` endpoint, as an optional field in the body: http://apidocs.cloudfoundry.org/251/spaces/update_a_space.html

It is still experimental, so it may change in the future.  We are hoping to make it GA soon.

Hope that helps,

@ericpromislow && @thausler786, CAPI team community pair
