### ISSUE TITLE
GET /v2/events next_url parameter changed

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry/capi-release#46]
## Issue

When I use next_url parameter to see List all Events through CAPI (GET /v2/events)
I think there is a changes with the next_url parameter

## Context
next_url parameter is different
To see next event log, "next_url" parameter not working

cf-release 251 (Contains CAPI release v1.15.0)
`"next_url": "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&results-per-page=50"`

cf-release 247 (Contains CAPI release v1.11.0)
`"next_url": "/v2/events?order-direction=asc&page=2&results-per-page=50"`

I didn't see anything about order-by parameter
https://apidocs.cloudfoundry.org/251/events/list_all_events.html

Has any plan about support next_url parameter?

## Expected result
As before, with next_url parameter can see next page events  

$ cf curl "/v2/events?order-direction=asc&page=2&results-per-page=50" | more
{
   "total_results": 2366,
   "total_pages": 48,
   "prev_url": "/v2/events?order-direction=asc&page=1&results-per-page=50",
   "next_url": "/v2/events?order-direction=asc&page=3&results-per-page=50",
   "resources": [
      {
         "metadata": {
            "guid": "bef7dbbe-7a64-4de3-8d58-93bfc2572c84",
            "url": "/v2/events/bef7dbbe-7a64-4de3-8d58-93bfc2572c84",
            "created_at": "2017-03-14T01:14:28Z",
            "updated_at": "2017-03-14T01:14:28Z"
         },
         "entity": {
            "type": "audit.app.process.crash",
..
..
..
## Current result

$ cf curl  "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&results-per-page=50"
{
   "code": 10012,
   "description": "Cannot order by: id",
   "error_code": "CF-OrderByParameterInvalid"
}

**Comment by zrob** [comment]
@mjsjinsu thanks for reporting this issue.

We have a [duplicate issue](https://github.com/cloudfoundry/cloud_controller_ng/issues/803) on the cloud controller repo

Closing this in favor of the linked issue
