### ISSUE TITLE
Inconsistent routes between CC and BBS

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/capi-release#50]
We're seeing a strange issue where `cf apps` lists this app as running and with a route to it configured:
```
$ cf apps
Getting apps in org my-org / space my-space as myuser...
cf app OK

name         requested state   instances   memory   disk   urls
my_app       started           1/1         256M     1G     my_app.mydomain.net
```

But when curling the app, the gorouter returns 404:

```
$ curl  my_app.mydomain.net
404 Not Found: Requested route ('my_app.mydomain.net') does not exist.
```

We checked BBS and indeed its routes for that app is empty:
```json
"routes": {
    "cf-router": [],
    "..."
}
```

This didn't just happen to one app, but actually to 16 out of 400, which were not touched at the time through `cf` or similar.

There are 2 questions now:
1. How was it possible that those routes got lost in the first place when the apps and their routes where not touched? Or, asked differently: Is it possible that for some reason CC/nsync removed the routes temporarily and then dropped the necessary re-addition accidentally, maybe because BBS wasn't up temporarily or whatever?

2. Given that this is the current state, shouldn't the nsync-bulker find this missing route and add it? After looking at nsync-bulker my understanding is that its stale-detection logic does not look at route discrepancies. Should it? This last piece is underlined by the fact that temporarily mapping an additional route also made the old one working again. So the trigger was enough to sync (through nsync-listener) what's in CC into the BBS.

**Steps to Reproduce**

Unfortunately, we don't know how to reproduce this. This issue is more aimed at understanding what could have caused this situation and if a change in the nsync-bulker might be necessary.

Thanks,
Peter

/cc @smoser-ibm @julzdiverse

**Comment by shiyan0109** [comment]
any updates?

**Comment by ljfranklin** [comment]
@petergtz For question 2 "shouldn't the nsync-bulker find this missing route and add it? ", the nsync and new Ruby sync rewrite only compare the last updated time for a process in CCDB and check it against the time included in the LRP annotation. Each time the routes change in CC, we manually notify diego of that change (like [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/process_route_handler.rb)) however the sync job won't notice a route mismatch. Ping @zrob to see if not considering routes is a bug or an explicit design decision.

For question 1 "How was it possible that those routes got lost in the first place?" we're still not sure. Do your sync logs show either "found-stale-lrp" or "found-missing-desired-lrp" (see [here](https://github.com/cloudfoundry/nsync/blob/5a15eb29fb0acc23b34993ea326b1c76d9017265/bulk/app_differ.go#L74-L94))? We've had bugs in the past around race conditions in the sync job, it would be good to know whether the sync job itself was responsible for re-submitting LRPs for your routeless apps.

**Comment by petergtz** [comment]
@zrob Could you comment on question 2?

@ljfranklin 

> Do your sync logs show either "found-stale-lrp" or "found-missing-desired-lrp"

We don't have those logs anymore. We are currently working on retaining them longer in the future. Once we see this issue again, we can then check our logs as you suggested.

**Comment by zrob** [comment]
Modifying routes use to cause an app's updated_at value to be [modified](https://github.com/cloudfoundry/cloud_controller_ng/blob/a79b5588345bac8f1f2f7d05e06c05ef8666bb0c/app/models/runtime/app.rb#L717).

So yes, I would expect out of sync routes to get resolved by the bulker.

**Comment by matt-royal** [comment]
Thanks, Zach. It sounds like the plan is to wait until this happens again and then @petergtz can send us the logs. I don't think there's much we can do until we have more information.

Matt & @ericpromislow

**Comment by petergtz** [comment]
@zrob Thanks for the clarification.

@matt-royal Sounds reasonable. I'll close this issue for now and will re-open in case we see this again and have more information to troubleshoot.
