### ISSUE TITLE
un-namespace `release_level_backup` property

### ISSUE THREAD

**Issue by flangewad** [cloudfoundry/capi-release#58]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

un-namespace `release_level_backup` property

## Context

The `release_level_backup` property here: https://github.com/cloudfoundry/capi-release/blob/develop/jobs/bbr-cloudcontrollerdb/spec#L19 is currently namespaced with cloudcontroller (job name), probably because it was modelled after the [bbr exemplar release](https://github.com/cloudfoundry-incubator/exemplar-backup-and-restore-release).

We (bbr) have recently learned that the convention for new job-level properties is for there not to be any namespacing, so we've updated our exemplar release. Could you un-namespace the `release_level_backup` property in your release?

**Comment by zrob** [comment]
Resolved in https://github.com/cloudfoundry/capi-release/pull/57

**Comment by tinygrasshopper** [comment]
@zrob there are other unnamespaced job specs in the `capi-release`
For example:
https://github.com/cloudfoundry/capi-release/blob/7c6ba63e0af00a18f5b000ff26c8f66760f7cf9c/jobs/bbr-cloudcontrollerdb/spec#L19
https://github.com/cloudfoundry/capi-release/blob/7c6ba63e0af00a18f5b000ff26c8f66760f7cf9c/jobs/tps/spec#L104
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L861

Can you please re-open this issue?

**Comment by tcdowney** [comment]
@Gerg we're going to reopen this. It's analogous to #57, but not the same so we should do it.

**Comment by Gerg** [comment]
Theses properties will no longer be namespaced in capi-release 1.44.
