### ISSUE TITLE
cloud_controller_ng pre-restore-lock exits before monit finished

### ISSUE THREAD

**Issue by edwardecook** [cloudfoundry/capi-release#60]
## Issue
For `cloud_controller_ng` the `pre-restore-lock` script does not wait till `monit` has fully stopped the jobs. So in the case that the restore is *very* quick, the subsequent `post-restore-unlock` script fails.

## Context
Running [DRATS](https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests)

## Steps to Reproduce
On a `cloud_controller_ng` job run `/var/vcap/jobs/cloud_controller_ng/bin/bbr/pre-restore-lock && /var/vcap/jobs/cloud_controller_ng/bin/bbr/post-restore-unlock`

## Expected result
Success, ends in a state where everything is currently running.

## Current result
Failing with stderr output `monit: action failed -- Other action already in progress -- please try again later`. `monit summary` shows that workers are down.

## Possible Fix
Wait for `monit` actions to complete in pre-restore-lock before exiting.

**Comment by Gerg** [comment]
Fixed here: https://github.com/cloudfoundry/capi-release/commit/e25b1325930b214dbbb9e0aea718e84ef862c03e

Please re-open if you still see this issue.
