### ISSUE TITLE
Please add patch for nginx-http-upload-module

### ISSUE THREAD

**Issue by aloismayr** [cloudfoundry/capi-release#61]
## Issue

The patch for the http-upload-module of nginx seems not to be included in the shipped nginx binary. Please review [nginx-upload-module commit aba1e3f](https://github.com/vkholodkov/nginx-upload-module/commit/aba1e3f34c754551f4f49e572bc86863d535609d) 

## Context

Wrong initialization of upload path cause segmentation faults. We can observe this behavior when Dynatrace agent instruments the nginx.

## Steps to Reproduce

Add Dynatrace agent to cloud_controller VM, restart nginx, cf push an app.

## Expected result

App pushed to CF successfully

## Current result

Nginx causes segmentation faults.

## Possible Fix

https://github.com/vkholodkov/nginx-upload-module/commit/aba1e3f34c754551f4f49e572bc86863d535609d

Latest commit from 2.2 branch

**Comment by anniesing** [comment]
Hi @aloismayr, 

Thanks for reaching out. What version of CAPI are you using? We see the nginx fix on our current branch, but need to know which version needs patching in your case.

Thanks,
- CAPI Interrupt Pair Annie and @elenasharma

**Comment by aloismayr** [comment]
Hi @anniesing, @elenasharma 

At least the Pivotal ERT version 1.11.7 - 1.12.2 are affected. According to Pivotal's release notes the capi release versions are: 1.28.0 and 1.40.0.

Please note that the official source download package of the release 2.2.0 (tag) does not contain the fix, but the branch 2.2.

Thanks! - Alois

**Comment by aloismayr** [comment]
Thanks @anniesing & @elenasharma !
