### ISSUE TITLE
cloud_controller_ng pre-backup-lock does not work when there is more than 1 CC instance

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/capi-release#63]
## Issue

When there is more than 1 CC (the multi-az case is most common), the `pre-backup-lock` script fails when running bbr because the api is never [unavailable](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/templates/pre-backup-lock.sh.erb#L19) because bbr runs these scripts serially (I think).

## Steps to Reproduce

Deploy cf with > 1 instance of the `api` job and attempt to run `bbr`.

## Current result

Failure text from `bbr` should look something like:
```
...
[bbr] 2017/10/09 16:57:36 INFO - Locking cloud_controller_ng on api/34b834f6-f161-485d-89d1-2f507e49b8b3 for backup...
[bbr] 2017/10/09 16:59:19 INFO - Done.
[bbr] 2017/10/09 16:59:19 ERROR - pre-backup-lock script for job cloud_controller_ng failed on api/34b834f6-f161-485d-89d1-2f507e49b8b3.
Stdout: 0
Endpoint https://api.apps.bam-bbr.cf-app.com/ did not go down after 90 seconds

Stderr:
...
```

**Comment by Gerg** [comment]
Fixed in https://github.com/cloudfoundry/cloud_controller_ng/commit/c443d7bfc6a043537e95e53c13ab73bf59eae7a5.

Please re-open if you are still seeing this issue after the next CAPI release.
