### ISSUE TITLE
some clock_jobs never run if last_completed_at < last_started_at value

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/capi-release#66]
## Issue
In a scenario where a clock_job's last_completed_at value is less than the last_started_at value, any job without a defined timeout value will never execute.  This can happen if the job or server crashes before updating the db.  
The `need_to_run_job` method in /lib/cloud_controller/clock/distributed_executor.rb will always evaluate as nil rather than true or false.
For some reason, the `cc.jobs.global.timeout_in_seconds` property isn't being applied to jobs that don't have their own explicit value set.

After adding some simple debug lines to the code:

     def need_to_run_job?(job, interval, timeout, fudge=0)
      last_started_at = job.last_started_at
      return true if last_started_at.nil?

      last_completed_at = job.last_completed_at
      @logger.info "debug_line:  last_completed_at = #{last_completed_at}"
      interval_has_elapsed = now >= (last_started_at + interval - fudge)
      @logger.info "debug_line:  interval_has_elapsed = #{interval_has_elapsed}"
      last_run_completed = last_completed_at && (last_completed_at >= last_started_at)
      @logger.info "debug_line:  last_run_completed = #{last_run_completed}"
      timeout_elapsed = timeout && (now >= (last_started_at + timeout))
      @logger.info "debug_line:  timeout value = #{timeout}"
      @logger.info "debug_line:  timeout_elapsed = #{timeout_elapsed}"
      @logger.info "debug_line:  need_to_run_job = #{interval_has_elapsed && (last_run_completed || timeout_elapsed)}"
      interval_has_elapsed && (last_run_completed || timeout_elapsed)
    end

Here is the output:

`"timestamp":1510261901.005922, "message":"debug_line:  Job name = pending_droplets"`
`"timestamp":1510261901.0065062,"message":"debug_line:  last_completed_at = 2017-10-09 19:36:00 UTC"`
`"timestamp":1510261901.0071208,"message":"debug_line:  interval_has_elapsed = true"`
`"timestamp":1510261901.0076826,"message":"debug_line:  last_run_completed = false"`
`"timestamp":1510261901.0081966,"message":"debug_line:  timeout value = "`
`"timestamp":1510261901.0087192,"message":"debug_line:  timeout_elapsed = "`
`"timestamp":1510261901.0092213,"message":"debug_line:  need_to_run_job = "`
`"timestamp":1510261901.0098224,"message":"Skipping enqueue for pending_droplets. Job last started at 2017-11-09 19:46:06 UTC, last completed at 2017-10-09 19:36:00 UTC, interval: 300"`

**Comment by rainmaker** [comment]
Hi @jmprice, 

Wanted to follow up on this issue. We ended up fixing it by revamping the `need_to_run_job?` method, replacing much of the the timestamp arithmetic with simpler checks. If a job was in-progress on a crashed worker VM, we should now wait until that job's timeout (or the global job timeout) and then re-queue the job. 

Let us know if you have any questions! The fix should be available in an upcoming CAPI release (~1.46.0)

Raina
CF CAPI team
