### ISSUE TITLE
Deploy succeeded but ruby_buildpack was missing

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/capi-release#69]
## Issue

We deployed CAPI 1.40.0 to Azure. The deploy succeeded but trying to push an app failed due to the "ruby_buildpack" not being present in the CAPI DB (although other buildpacks were present).

In the post-start log we see:

```
[2017-12-22 00:05:36+0000] + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2017-12-22 00:05:39+0000] SEQUEL DEPRECATION WARNING: ...
[2017-12-22 00:05:40+0000] + [[ 0 -ne 0 ]]
[2017-12-22 00:05:40+0000] + popd
[2017-12-22 00:05:40+0000] + exit 0
```

In the cloud_controller_ng.log, we see:

```
{"timestamp":1513901227.9414902,"message":"Buildpack ruby_buildpack failed to install or update. Error: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: Net::OpenTimeout>>","log_level":"error","source":"cc.background","data":{},"thread_id":47339562332440,"fiber_id":47339590905600,"process_id":12124,"file":"/var/vcap/data/packages/cloud_controller_ng/46683eb3e4b842f2d70df86eb544df41b20d252f/cloud_controller_ng/app/jobs/runtime/buildpack_installer.rb","lineno":38,"method":"rescue in perform"}
{"timestamp":1513901227.9422777,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"Net::OpenTimeout\", \"error_code\"=>\"CF-ConnectionFailed\", \"backtrace\"=>[\"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/net/http.rb:930:in `connect'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/net/http.rb:852:in `start'\", \"/var/vcap/packages/ruby-2.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/http_response_helper.rb:27:in `set_up_response'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:143:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/retry_policy.rb:41:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/retry_policy.rb:41:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:104:in `block in with_filter'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/signer_filter.rb:28:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/signer_filter.rb:28:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:104:in `block in with_filter'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/service.rb:36:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/filtered_service.rb:34:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-core-0.1.8/lib/azure/core/signed_service.rb:41:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-storage-0.12.1.preview/lib/azure/storage/service/storage_service.rb:53:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-storage-0.12.1.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/azure-storage-0.12.1.preview/lib/azure/storage/blob/block.rb:154:in `put_blob_block'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-azure-rm-0.3.1/lib/fog/azurerm/requests/storage/put_blob_block.rb:12:in `put_blob_block'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/fog-azure-rm-0.3.1/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb:74:in `block (2 levels) in multipart_save_block_blob'\"]}}","log_level":"error","source":"cc.background","data":{"job_guid":"f44f29ac-94c8-495a-8e33-55d597f14d45"},"thread_id":47339562332440,"fiber_id":47339590905600,"process_id":12124,"file":"/var/vcap/data/packages/cloud_controller_ng/46683eb3e4b842f2d70df86eb544df41b20d252f/cloud_controller_ng/app/jobs/logging_context_job.rb","lineno":43,"method":"block in log_error"}
```

Seems like there are two issues:

- Why did the deploy succeed despite the buildpack upload failing? Is the buildpack upload asynchronous?
- Should the fog azure client have retried on networking errors from Azure? I think it is standard practice on most IaaS clients to retry on 500s and temporary networking errors with an exponential backoff.

Let us know if you need any additional info.

@ljfranklin && @utako, Former CAPIbaras

**Comment by bingosummer** [comment]
Is the issue resolved?

**Comment by kkallday** [comment]
This is still an issue in our pipeline. We notice it fairly often.

**Comment by bingosummer** [comment]
@kkallday @ljfranklin 
We saw a similar issue. In this issue, the version of "azure-core" is `0.1.12`, which has a bug.
https://github.com/Azure/azure-storage-ruby/issues/118

From your logs, the version of "azure-core" is `0.1.8`. Could you please upgrade `azure-core` to the latest version `0.1.14` and see whether it's fixed?

CC: @yaxia @katmsft

**Comment by markstokan** [comment]
+1

CF Toolsmiths team is running into this error after moving our file storage to Google Storage Buckets for GCP deployed PCFs.  Added detailed notes to the Tracker story at:

https://www.pivotaltracker.com/n/projects/966314/stories/153866386

**Comment by mjj209** [comment]
The CF Toolsmiths ran into this again today with the SF-PAS 2.1.10 I thought the GCS fixes had made it into SF-PAS 2.1.10? Maybe the deploy still is not checking to see if the buildpack uploading is failing?

We are considering switching back to the file server VM, but it would come at an additional cost on GCP.

**Comment by markstokan** [comment]
CF Toolsmiths just saw a 2.3.0 PAS deployment fail using `External Google Cloud Storage with Service Account` blobstore

/var/vcap/sys/log/cloud_controller_ng/ cloud_controller_ng.log
```
{"timestamp":1537980291.5070543,"message":"Buildpack ruby_buildpack failed to install or update. Error: #<CloudController::Blobstore::BlobstoreError: execution expired>","log_level":"error","source":"cc.background","data":{},"thread_id":47144284327780,"fiber_id":47144307974280,"process_id":28075,"file":"/var/vcap/data/packages/cloud_controller_ng/11dcb40c2172fd80b7a74948e80fbd3b12544ac7/cloud_controller_ng/app/jobs/runtime/create_buildpack_installer.rb","lineno":25,"method":"rescue in perform"}
```

**Comment by markstokan** [comment]
CF Toolsmiths ran into this issue today with a GCP deployment using Internal WebDAV storage.

client cloud_controller_ng.log attached

we could not find evidence of any errors in the server blobstore logs.

[tracker.txt](https://github.com/cloudfoundry/capi-release/files/2447856/tracker.txt)

**Comment by cwlbraa** [comment]
so buildpack install uploads do, in fact, happen asyncronously on cc local workers. part of this is so uploads can be done with some degree of parallelism, part of it is because we might time out the deploy if we actually uploaded all of them during it. 

the errors you attached imply that the upload timed out at least once out of its 3 retries. it's possible that this is due to network or compute flakiness or ever-so-slightly underprovisioned blobstores.

**Comment by tcdowney** [comment]
We hope to address this in https://www.pivotaltracker.com/story/show/161296753.

**Comment by mjj209** [comment]
@tcdowney @cwlbraa Toolsmiths saw this a few more times earlier this week. If we were to try and mitigate the issue of ever-so-slightly underprovisioned blobstores, the blobstores being a FileServerVM, What would we increase?

- CPU on the fileserver VM (Currently 1)
- Memory on the fileserver VM (Current 4GB)
- Transition to SSD's on the Boot Disk/Persistent Disk (Currently standard disks)

**Comment by tcdowney** [comment]
@mjj209 

Do you have any load metrics from those VMs during blobstore operations?

My gut tells me that giving it more than a single vCPU will help the most (we try to do two concurrent buildpack uploads during buildpack installation) and the fileserver VM is likely being constrained by the single CPU.

Next, faster storage would always help as well, but I'd try increasing the CPU count first.

**Comment by mjj209** [comment]
I re-deployed the BlobStore VM with a med.disk type with 2 CPUs. The load profile after it was created & smoke tests passed showed:

```
pivotal@mangotango-ops-manager:~$ bosh -e gcp vms --vitals
Using environment '10.0.0.5' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

Task 137. Done

Deployment 'cf-28b66d7a6e3d8c0e48ea'

Instance                                        Process State  AZ             IPs       VM CID                                   VM Type                      Active  VM Created At                 Uptime         Load              CPU    CPU   CPU   CPU   Memory        Swap      System      Ephemeral   Persistent  
                                                                                                                                                                                                                   (1m, 5m, 15m)     Total  User  Sys   Wait  Usage         Usage     Disk Usage  Disk Usage  Disk Usage  
blobstore/8c485763-2610-4966-a758-abf6e268577e  running        us-central1-a  10.0.4.6  vm-478baa3b-c060-4172-4546-74c826c4b568  medium.disk                  true    Wed Oct 31 23:39:03 UTC 2018  0d 0h 4m 49s   0.02, 0.07, 0.03  -      0.1%  0.2%  0.1%  10% (400 MB)  0% (0 B)  50% (36i%)  0% (0i%)    7% (0i%)  
```

So it doesn't seem like much load. It's fairly trivial to add an additional CPU for this resource, so I think we'll give that a shot. These failures happen a couple times a month, so we'll find out in about a month if the fix has improved the reliability.

**Comment by tcdowney** [comment]
@mjj209 

For your specific environments I think the most interesting time to collect load metrics would be during the initial deployment while the `cloud_controller_ng` job is running its [post-start](https://github.com/cloudfoundry/capi-release/blob/f61b511ed45da3b03e99a848db04d046def4c44a/jobs/cloud_controller_ng/templates/post-start.sh.erb) script since that's when buildpack installation happens.

Apart from that, if you have any users who are pushing a large number of apps and testing the app evacuation of the Diego cells, that would also be an interesting time to collect load metrics.

**Comment by mjj209** [comment]
@tcdowney @ljfranklin Toolsmiths bumped the file server VM for PAS on GCP from 1 CPU to 2 CPUs, and we haven't had a failure in ~3 weeks. We're declaring local success on this issue. We used to have ~5 failures per month out of 4,000 due to this issue.

I'm not sure if the PAS defaults should change?

**Comment by charleshansen** [comment]
For what it is worth, we do have improved buildpack upload retry logic (from https://www.pivotaltracker.com/story/show/161296753) starting in capi release `1.73.0`. I'm curious if this fixes the issue.

Otherwise, I agree we should look into changing the PAS defaults.

**Comment by ljfranklin** [comment]
Thanks for digging in @mjj209! Added a story to bump the default CPU sizing here: https://www.pivotaltracker.com/story/show/162225798. Having the retries is a nice safety net but we shouldn't need to rely on retries to successfully upload buildpacks in the happy path case.

**Comment by selzoc** [comment]
Looks like the above story was accepted back in December, so closing this issue
