### ISSUE TITLE
Please remove "domain" property in job specs

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/capi-release#7]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The top-level `domain` property in several job specs should be removed in favour of just using `system_domain`.

## Context

The property is specified in a few jobs:

* [cloud_controller_worker](https://github.com/cloudfoundry/capi-release/blob/3b1efa772fea38048b05d29b2a5349c92dbb4dca/jobs/cloud_controller_worker/spec#L34-L35)
* [cloud_controller_clock](https://github.com/cloudfoundry/capi-release/blob/3b1efa772fea38048b05d29b2a5349c92dbb4dca/jobs/cloud_controller_clock/spec#L28-L29)
* [blobstore](https://github.com/cloudfoundry/capi-release/blob/3b1efa772fea38048b05d29b2a5349c92dbb4dca/jobs/blobstore/spec#L51-L52)
* [cloud_controller_ng](https://github.com/cloudfoundry/capi-release/blob/3b1efa7/jobs/cloud_controller_ng/spec#L49-L50)

Fixing this issue will help unblock [this story](https://www.pivotaltracker.com/story/show/118256181) to remove the property from manifest generation templates and confusing documentation.

The `domain` property is a constant source of confusion.  See this [mailing list thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/MR4MD72XCSQC7KR33E7LSE5Z3ZAGEWW4/).  (Examples of the confusion between `domain` and `system_domain` can be found regularly on the mailing lists, GitHub issues, and Slack questions).

## Steps to Reproduce

N/A

## Expected result

No more tears.

## Current result

Tears.

## Possible Fix

Remove properties from job specs, and references to them in job ERB templates.

## `name of issue` screenshot

N/A

**Comment by simonleung8** [comment]
Thanks for filing the issue. 

We have an upcoming story to address the exact issue. You can track it [here](https://www.pivotaltracker.com/story/show/117401791)

Thanks
@simonleung8

**Comment by utako** [comment]
Hi @Amit-PivotalLabs,

We have completed the work in capi-release to get rid of `properties.domain` in favor of `properties.system_domain`. 

I'm closing this issue, please feel free to reopen if you have any concerns.

@utako, CF CAPI Team
