### ISSUE TITLE
The job `cloud_controller_ng` failed when updating instance api

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/capi-release#71]
Please see https://github.com/cloudfoundry/cloud_controller_ng/issues/1047 for detailed information.

After some investigating, I found the root cause.
In https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/monit, the timeout to start the process `cloud_controller_ng` is 30 seconds.
In https://github.com/cloudfoundry/capi-release/blob/develop/shared_job_templates/blobstore_waiter.sh.erb, `wait_for_blobstore` will try 30 times to curl blobstore and sleep 1 second between each try. It means, `wait_for_blobstore` may return "Blobstore is available" after 30s, because sometimes blobstore needs a longer time to be ready. But at that moment, monit regarded `cloud_controller_ng` as failed. In fact, the process `cloud_controller_ng` has been up.

The possible fix is to increase the timeout in the monit file.

**Comment by charleshansen** [comment]
@bingosummer is this a problem that you still have? CC uses bpm now, which should fix the general start time. There have also been some blobstore improvements since when this issue was first filed.
