### ISSUE TITLE
Apps pushed with `v3-push --no-start` cannot `build`

### ISSUE THREAD

**Issue by mingxiao** [cloudfoundry/capi-release#77]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Apps pushed with `v3-push --no-start` cannot `build`

## Context

We `v3-push --no-start` an app to apps manager. In Apps Manager we tried to start the app. Starting the app, in Apps Manager, consist of building a droplet if one does not exist.

## Steps to Reproduce

`v3-push --no-start` this app: https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/syslog-drain-listener

the api calls we are making in order:
1. `v3/apps/66a01d5a-733c-457d-9d71-b3848c0e455c/packages`
2.  POST to `/api/v3/builds` with package_guid returned from [1]
3. `v3/builds/8cecc7f9-96fa-45d3-ac14-cb3a0e90ae15`, build_guid returned from [2] --- leads to error

## Expected result

The build succeeds and the app starts

## Current result

The build fails with 
```
"state": "FAILED",
  "error": "NoAppDetectedError - An app was not successfully detected by any available buildpack",
```

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

<img width="1281" alt="screen shot 2018-02-14 at 2 46 12 pm" src="https://user-images.githubusercontent.com/1500022/36232236-d9889676-1195-11e8-9fdd-0f84fa3311f6.png">

**Comment by ericpromislow** [comment]
You need to set an environment variable for GOPACKAGENAME so the stager knows what to do.  Here's the pseudo-script I used to get this up and running:
```
#!/not/exactly/a/shell/script

# Vars to set in advance:
DOMAIN_NAME= # mydomain.company.com
SPACE_NAME=  # myspace
TARGET_HOST_NAME= # myapp

# Push an app using the v3 api and set the staging-env var before continuing

cd $GOPATH/src/github.com/cloudfoundry/cf-acceptance-tests/assets/syslog-drain-listener

CF_API_ENDPOINT=$(cf api | grep -i "api endpoint" | awk '{print $3}')

SPACE_GUID=$(cf space `cf target | tail -n 1 | awk '{print $2}'` --guid)

APP_NAME=syslog-drain-listener

cf v3-push $APP_NAME --no-start

APP_GUID=$(cf curl /v3/apps?names=$APP_NAME | jq -r '.resources[0].guid')

cf curl -X PATCH /v3/apps/$APP_GUID/environment_variables -d '{ "var" : {"GOPACKAGENAME": "main"} }'

PACKAGE_GUID=$(cf curl /v3/packages -X POST -d "$(printf '{"type":"bits", "relationships": {"app": {"data": {"guid": "%s"}}}}' "$APP_GUID")" | tee /dev/tty | jq -r .guid)

zip -r my-app.zip *

curl -k "$CF_API_ENDPOINT/v3/packages/$PACKAGE_GUID/upload" -F bits=@"my-app.zip" -H "Authorization: $(cf oauth-token | grep bearer)"

BUILD_GUID=$(cf curl /v3/builds -X POST -d "$(printf '{ "package": { "guid": "%s" }}' "$PACKAGE_GUID")" | tee /dev/tty | jq -r .guid)

# You could write a while loop to continue as long as the build is STAGING, or do this manually:

watch cf curl /v3/builds/$BUILD_GUID

DROPLET_GUID=$(cf curl /v3/builds/$BUILD_GUID | jq -r '.droplet.guid')

cf curl /v3/apps/$APP_GUID/relationships/current_droplet -X PATCH -d "$(printf '{"data": {"guid": "%s"}}' "$DROPLET_GUID")"

# These vars need to be set at the top
CF_TRACE=true cf create-route $SPACE_NAME $DOMAIN_NAME -n $TARGET_HOST_NAME

# **** No obvious way to get this quickly via the API, so just copy and paste (which is why this isn't a script)

ROUTE_GUID=[copy route's GUID under metadata->guid of the last response]

ROUTE_MAPPING=$(printf '{"relationships": {"route": {"guid": "%s"}, "app": {"guid": "%s"} } }' "$ROUTE_GUID" "$APP_GUID")

cf curl /v3/route_mappings -X POST -d "$ROUTE_MAPPING"

cf curl /v3/apps/$APP_GUID/actions/start -X POST
```

**Comment by zrob** [comment]
To expand on this a bit.  The root reason is that v3 push does not care about manifests yet.  That work is currently in flight.
