### ISSUE TITLE
Url-encode the database username

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/capi-release#79]
## Issue

Azure MySQL database's server login name is in the format `username@servername`.
https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-azure-portal#get-the-connection-information

To workaround this issue, we can use `username%40servername` as the database username. But the format which [backup-and-restore-sdk-release](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release) requires is `username@servername`. This is a conflict.

## Expected result

When using external databases, we can use `username@servername` as the database username. Both capi-release and backup-and-restore-sdk-release can accept the format.

## Current result

We need to use `username%40servername` as the database username for capi-release. But backup-and-restore-sdk-release doesn't accept it.

## Possible Fix

https://github.com/bingosummer/capi-release/commit/2dfd9524f6a7231bb85078a81342e6a3bf9ed409

**Comment by bingosummer** [comment]
Ping...
Does the PR make sense? If not, I'm happy to discuss more.

**Comment by zrob** [comment]
should be resolved in next capi-release.  conversation in pr #80
