### ISSUE TITLE
Automatically assigning subdomain routes to apps within a space

### ISSUE THREAD

**Issue by benjefferies** [cloudfoundry/capi-release#85]
As a developer using the cloudfoundry platform it would be really useful to be able to namespace the hostname of apps per space so that we only need one manifest per application and we don't need to add custom routes for every deployment to each space.

An example:
I an app I would like to deploy to two spaces: dev and ci.
The app name in my manifest is: foobar
When I deploy my service to the dev space I would get a route: foobar.dev.mydomain.com
When I deploy my service to the ci space I would get a route: foobar.ci.mydomain.com

Currently this would fail as the dev deployment would take the route foobar.mydomain.com and I would have to specify the host for the ci deployment.

There are workarounds for this but it would be much more seamless if spaces could be assigned subdomains

**Comment by selzoc** [comment]
@benjefferies I don't think this is something we're going to pursue at the moment.  Right now we're focused on org-level domains.

If it helps, we have the concept of a [space manifest](http://v3-apidocs.cloudfoundry.org/version/3.78.0/index.html#space-manifest) which allows you to define multiple apps in a space in the same manifest.
