### ISSUE TITLE
Download droplet/package fails when using internal S3-compatible blobstore

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/capi-release#90]
## Issue

We're deploying [Minio](https://github.com/minio/minio-boshrelease) as an internal blobstore for CF. It's an s3-compatible blobstore so CAPI is using the fog-aws gem. The normal blobstore operations are working fine, but we have a couple CATs tests failing when trying to download droplets/packages from CF to the Concourse worker (http://v3-apidocs.cloudfoundry.org/version/3.48.0/index.html#download-package-bits). CAPI hands out the internal URL `minio-server.service.cf.internal` which is not resolvable from the Concourse worker.

## Possible Fix

Could CAPI support a `blobstore.internal: true` or similar which tells CAPI to proxy the download as it does with WebDav?

**Comment by tcdowney** [comment]
@ljfranklin is this still an issue?

CC @crawsible

**Comment by selzoc** [comment]
Any updates here?
