### ISSUE TITLE
Information on CAPI release 1.49.6

### ISSUE THREAD

**Issue by sujittripathy** [cloudfoundry/capi-release#91]
## Issue

I would like to know what's the cf api version in `1.49.6` however, I am seeing `1.49.0` and `1.50.0` here (https://github.com/cloudfoundry/capi-release/tags) and not the exact version of `1.49.6`. Why I am referring this exact CAPI version because the Pivotal Cloud Foundry (aka PCF) 2.1 (https://docs.pivotal.io/pivotalcf/2-1/pcf-release-notes/runtime-rn.html#2.1.6) uses
the version of CAPI `1.49.6` so, I would like to know what's the changes made and what was the api end point version of that CAPI release.

**Comment by zrob** [comment]
PCF 2.1 is a custom distribution of this open source repository.  This means that Pivotal has made some changes on top of the open source 1.49.0 release and it is not available in this repository.  The release notes you linked above would be the best place to get information on updates.  

You can also take a look at the /v2/info endpoint of your Cloud Controller.  That should display the API version.  I don't believe it will be different from what is in 1.49.0.  The 1.49.x release should be the same API with the server having some bug and security fixes added.
