### ISSUE TITLE
cloud_controller_ng pre-start script fails to recover from interrupted db migration

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/capi-release#92]
## Issue

In CAPI 1.28.56, cloud_controller instance lost connection to database while performing a db migration in the pre-start script and could not recover.  

```
[2018-06-07 20:18:54+0000] + bundle exec rake db:migrate
[2018-06-07 20:21:56+0000] rake aborted!
[2018-06-07 20:21:56+0000] Sequel::DatabaseDisconnectError: Mysql2::Error: Lost connection to MySQL server during query
```

Subsequent migration attempts fail with errors 

```
[2018-06-07 20:22:01+0000] + echo 'Running migration try number 2 of 3'
[2018-06-07 20:22:01+0000] + bundle exec rake db:migrate
[2018-06-07 20:22:05+0000] rake aborted!
[2018-06-07 20:22:05+0000] Sequel::DatabaseError: Mysql2::Error: Duplicate column name 'requires'
```

## Context

Brand new PCF 1.11 deployment fails during ERT tile deployment with error

```
 Started updating instance cloud_controller > cloud_controller/bf048033-ffbb-489b-a4ab-599f1835e87a (0) (canary). Failed: Action Failed get_task: Task f572e110-a626-4744-6d2e-23b194417e15 result: 1 of 5 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: routing-api, route_registrar, consul_agent, syslog_forwarder. (00:07:08)
```

## Steps to Reproduce

I suppose you could purposely drop packets to the database while a migration was underway to reproduce this.

## Possible Fix

Drop the database on subsequent re-attempts to migrate the db?

**Comment by selzoc** [comment]
Hi @markstokan !  This is a known issue with MySQL not allowing schema alterations to be made in a transactional context.  We try to make our migrations small so as to reduce the risk of failure on retries, but sometimes they are unavoidable.

Depending on the migration, manual database intervention may be required, so we don't have CAPI do anything automatic to recover from these errors.

As always, for any PCF issues, we encourage folks to reach out to Pivotal support, which has plenty of experience for these situations.

Thanks,
Chris
