### ISSUE TITLE
Capi v1.60.0 broke our route services

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/capi-release#93]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CAPI v1.60.0 errors when somebody tries to bind a "route service" instance to an app. We actually *used* this to provide additional functionality for our route services which is now broken. 

In order to provide an extra layer of protection and assurance for our apps our route services add an HMAC signature to authenticated requests. The shared key to validate this signature is provided to the app via normal service binding credentials. 

That's no longer possible now. It should be up to the route service broker to decided whether or not instances can be bound to apps or not. That's easily distinguishable by inspecting the bind details AppGuid and bind resource Route fields.

Please revert this new behaviour.

```
Binding service xxx-protectr to app xxx in org xxx / space xxx as xxx...
FAILED
Server error, status code: 422, error code: 60027, message: Route services cannot be bound to apps
```

**Comment by tcdowney** [comment]
Sorry about this @x6j8x, I reverted the commit that introduced that validation.

We are still going to do a little more work in this area to prevent the source of the `UnknownError`s that lead to that validation being introduced, but it should not break this behavior again. That's being done in https://www.pivotaltracker.com/story/show/158398455 if you're interested.

**Comment by x6j8x** [comment]
@tcdowney thanks! any idea when the next release will be cut?

**Comment by tcdowney** [comment]
Not sure, but hopefully not too long from now. I know there are a couple of other bugs we're hoping to get fixed in it. Sorry again for the inconvenience!

**Comment by tcdowney** [comment]
@x6j8x capi-release 1.61.0 was just cut which includes this fix:

https://github.com/cloudfoundry/capi-release/releases/tag/1.61.0
