### ISSUE TITLE
nfs mounter not working with Stemcell Ubuntu Xenial

### ISSUE THREAD

**Issue by Onke** [cloudfoundry/capi-release#95]
## Issue

NFS share mount with capi-release on Ubuntu Xenial stemcell not working

## Context

We were using the Ubuntu Trusty bosh stemcell to mount a NFS share. Everything worked fine. Now we want to use the Ubuntu Xenial Bosh Stemcell, which does not include the nfs-common package anymore. We can't mount the NFS anymore.

## Steps to Reproduce

Bosh deployment with Ubuntu Xenial stemcell, try to mount a NFS share

## Expected result

NFS can be mounted successfully 

## Current result

NFS can't be mounted because nfs-common package is missing

## Possible Fix

Include nfs bits to capi-release 

## `name of issue` screenshot

-

**Comment by tcdowney** [comment]
Thanks for reporting this @Onke.

The Ubuntu Xenial stemcells removed some packages that were required for the `nfs_mounter` to work (namely `nfs-common` I think) and we have an existing story to investigate this and figure out how to get it working again:

https://www.pivotaltracker.com/story/show/158203210

For now, you'll need to continue using the Ubuntu Trusty stemcells until we can update the `nfs_mounter`.

**Comment by zrob** [comment]
the linked story has been completed and will be available in the next capi-release

closing for now.  

if you have issues after updating to a new capi-release please open a new issue and let us know
