### ISSUE TITLE
Possible for cloud controller to start when nfs not mounted without deployer knowing

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/capi-release#96]
## Issue
It appears to be possible to successfully deploy the CC with an nfs share that fails to mount.

## Context

The other day when doing a deploy that changed ip addresses of my CC job my deployment appeared to succeed but the nfs volume failed to mount on one of my CC instances.  The CC that failed to mount the NFS share happened to be the last instance of the deployment so buildpacks were uploaded to the bosh ephemeral disk.  This caused some odd and somewhat intermittent issues that were hard to identify. 

* https://cloudfoundry.slack.com/archives/C02FM2BPE/p1530566915000283
* https://cloudfoundry.slack.com/archives/C07C04W4Q/p1530567029000185
* https://www.pivotaltracker.com/story/show/158782168

## Steps to Reproduce

* Configure nfs_mounter job with an nfs share that doesn't exist or work
* Deploy CC with nfs_mounter job

## Expected result

* I would like to see deployment fail or nfs_mounter and/or cloud_controller to fail if nfs is inaccessible.

## Current result

Deployment succeeds and all jobs show healthy in monit.
NFS mount fails to mount and knows that it fails to mount but it nor CC actually let bosh know something is wrong.

## Possible Fix

Perhaps CC and/or nfs_mounter job can be augmented with a script that can detect if the share is mounted or not.   Below is a simple example of such a script:

```
    echo "Checking to see if nfs is mounted." >> ${LOG_DIR}/nfs_mounter.stdout.log
    nfs_check_attempts=0
    while [ "$(stat --format='%d%D' /)" = "$(stat --format='%d%D' $NFS_DIR)" ]; do
      sleep 1
      nfs_check_attempts=$((nas_check_attempts+1))
      echo "Failed to find NFS mount $nfs_check_attempts times." >> ${LOG_DIR}/nfs_mounter.stderr.log
      if [ $nfs_check_attempts = "20" ]; then
        echo "Timed out waiting for NFS mount to become available." >> ${LOG_DIR}/nfs_mounter.stderr.log
        exit 1
      fi
    done
    echo "NFS share mounted!" >> ${LOG_DIR}/nfs_mounter.stdout.log
```

Granted there are complexities like when to enable such a script in CC startup.  You might also think to punt on this issue and let the bits-service handle it.  Perhaps this issue can be used as reference for them in that case.

**Comment by tcdowney** [comment]
@youngm do you still see this happen when Cloud Controller is running in BPM? I know some stuff around where the `nfs_mounter` mounts the NFS share has changed and that BPM now has to share that mount with the container that CC is running in. Curious if this still happens.

If it does, we might be able to add some validation on startup to check the mount status like you're suggesting.

**Comment by youngm** [comment]
I finally found time to give it a try and the deploy failed with bad NFS!  Nice job!
